### EDA

In [265]:
import pandas as pd

In [266]:
pwd

'/home/florianriemann/spicy_projects/repos/garlic-boosting-student-code/10_week_project'

In [267]:
PATH = '/home/florianriemann/spicy_projects/repos/garlic-boosting-student-code/10_week_project/data/ml-latest-small/'

In [268]:
# extract the year from the title
# split the genres by | and do one-hot-encoding

movies = pd.read_csv(PATH + 'movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [269]:
# extract the year from the title
movies['year'] = movies['title'].str[-5:-1]
# transform year to pd datetime
movies.head()

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995

In [270]:
# clean the title from numbers and special characters
movies['title_clean'] = movies['title'].str[:-6]
movies.head()

,movieId,title,genres,year,title_clean
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,Toy Story
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995,Jumanji
2,3,Grumpier Old Men (1995),Comedy|Romance,1995,Grumpier Old Men
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,Waiting to Exhale
4,5,Father of the Bride Part II (1995),Comedy,1995,Father of the Bride Part II

In [271]:
# check if any movieId are duplicated
movies['title'].duplicated().sum()

5

In [272]:
# movies.iloc(movies['title'].duplicated())
movies['title'].duplicated().any()

True

In [273]:
movies[movies['title'].duplicated()]

,movieId,title,genres,year,title_clean
5601,26958,Emma (1996),Romance,1996,Emma
6932,64997,War of the Worlds (2005),Action|Sci-Fi,2005,War of the Worlds
9106,144606,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Romance|Thriller,2002,Confessions of a Dangerous Mind
9135,147002,Eros (2004),Drama|Romance,2004,Eros
9468,168358,Saturn 3 (1980),Sci-Fi|Thriller,1980,Saturn 3

In [274]:
# example of a duplicate
movies[movies['title'] == 'Emma (1996)']

      movieId        title                genres  year title_clean
650       838  Emma (1996)  Comedy|Drama|Romance  1996       Emma
5601    26958  Emma (1996)               Romance  1996       Emma

In [275]:
# lets remove duplicated rows by keeping only the last
movies = movies.drop_duplicates('title', keep='last')

In [276]:
# split the genres into dummies and concat with movies dataframe
dummy_genre = movies['genres'].str.get_dummies(sep='|')
movies = pd.concat([movies, dummy_genre], axis=1)
# drop column genres
movies.drop(columns=('genres'), inplace=True)
movies.head()

,movieId,title,year,title_clean,(no genres listed),Action,Adventure,Animation,Children,Comedy,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),1995,Toy Story,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),1995,Jumanji,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),1995,Grumpier Old Men,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),1995,Waiting to Exhale,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),1995,Father of the Bride Part II,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [277]:
movies.columns

Index(['movieId', 'title', 'year', 'title_clean', '(no genres listed)',
       'Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [278]:
movies.shape

(9737, 24)

In [279]:
links = pd.read_csv(PATH + 'links.csv')
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [280]:
links.shape

(9742, 3)

In [281]:
ratings = pd.read_csv(PATH + 'ratings.csv')
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [282]:
# can a user rate a movie more than once (maybe at another time)?
ratings.shape

(100836, 4)

In [283]:
# no, each movie was rated only once per user
ratings.groupby(['userId','movieId']).count().nunique()

rating       1
timestamp    1
dtype: int64

In [284]:
# drop the timestamp
ratings.drop(columns=['timestamp'], axis=0, inplace=True)
ratings

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [285]:
# join movies with ratings, so that we get the titles
#ratings = pd.concat([ratings, movies], axis=1, join="left")
ratings_extended =  pd.merge(ratings, movies, on="movieId")
ratings_extended

,userId,movieId,rating,title,year,title_clean,(no genres listed),Action,Adventure,Animation,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,1,4.0,Toy Story (1995),1995,Toy Story,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,5,1,4.0,Toy Story (1995),1995,Toy Story,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,7,1,4.5,Toy Story (1995),1995,Toy Story,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,15,1,2.5,Toy Story (1995),1995,Toy Story,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,17,1,4.5,Toy Story (1995),1995,Toy Story,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100731,610,160341,2.5,Bloodmoon (1997),1997,Bloodmoon,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
100732,610,160527,4.5,Sympathy for the Underdog (1971),1971,Sympathy for the Underdog,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
100733,610,160836,3.0,Hazard (2005),2005,Hazard,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
100734,610,163937,3.5,Blair Witch (2016),2016,Blair Witch,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
100735,610,163981,3.5,31 (2016),2016,31,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [286]:
# write datafarme 'ratings_extended' as csv
ratings_extended.to_csv('ratings_extended.csv')

In [287]:
ratings_extended = pd.read_csv('ratings_extended.csv')

/tmp/ipykernel_8717/1428709077.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  ratings_extended = pd.read_csv('ratings_extended.csv')

In [288]:
ratings_extended

,Unnamed: 0,userId,movieId,rating,title,year,title_clean,(no genres listed),Action,Adventure,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,1,1,4.0,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,5,1,4.0,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,7,1,4.5,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,3,15,1,2.5,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,17,1,4.5,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100731,100731,610,160341,2.5,Bloodmoon (1997),1997,Bloodmoon,0,1,0,...,0,0,0,0,0,0,0,1,0,0
100732,100732,610,160527,4.5,Sympathy for the Underdog (1971),1971,Sympathy for the Underdog,0,1,0,...,0,0,0,0,0,0,0,0,0,0
100733,100733,610,160836,3.0,Hazard (2005),2005,Hazard,0,1,0,...,0,0,0,0,0,0,0,1,0,0
100734,100734,610,163937,3.5,Blair Witch (2016),2016,Blair Witch,0,0,0,...,0,1,0,0,0,0,0,1,0,0
100735,100735,610,163981,3.5,31 (2016),2016,31,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [289]:
# get the mean rating of each movie
ratings_pivot_raw = ratings_extended.pivot(index='userId', columns='title', values='rating')
ratings_pivot_raw

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [290]:
ratings_pivot_raw.shape

(610, 9719)

In [291]:
ratings_pivot_raw.size

5928590

In [292]:
ratings_pivot_raw.isna().sum().sum()

5827854

In [293]:
# percentage of missing values
ratings_pivot_raw.isna().sum().sum()/ratings_pivot_raw.size

0.983008438768746

In [294]:
# axis is by default columns which is 0 = 'rows'
# axis rows is 1 = 'columns'

ratings_pivot_raw.mean().sort_values(ascending=False)

title
Watermark (2014)                                                               5.0
Connections (1978)                                                             5.0
Dream of Light (a.k.a. Quince Tree Sun, The) (Sol del membrillo, El) (1992)    5.0
Bill Hicks: Revelations (1993)                                                 5.0
Hellbenders (2012)                                                             5.0
                                                                              ...
Haunted House 2, A (2014)                                                      0.5
Ben-hur (2016)                                                                 0.5
Begotten (1990)                                                                0.5
Maria Bamford: The Special Special Special! (2012)                             0.5
Christmas Carol, A (1977)                                                      0.5
Length: 9719, dtype: float64

In [295]:
ratings_pivot_raw

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [296]:
ratings_pivot_raw.mean().mean()

3.26233463911876

In [297]:
global_mean = ratings_pivot_raw.mean().mean()

In [298]:
ratings_pivot = ratings_pivot_raw.fillna(global_mean)

### Export 1

In [299]:
ratings_pivot

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,4.000000,3.262335
2,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
3,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
4,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
5,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
607,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
608,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,4.500000,3.500000,3.262335,3.262335,3.262335
609,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
610,4.000000,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.500000,3.262335,...,3.262335,4.000000,3.500000,3.000000,3.262335,3.262335,2.000000,1.500000,3.262335,3.262335

In [300]:
ratings_extended

,Unnamed: 0,userId,movieId,rating,title,year,title_clean,(no genres listed),Action,Adventure,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,1,1,4.0,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,5,1,4.0,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,7,1,4.5,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,3,15,1,2.5,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,17,1,4.5,Toy Story (1995),1995,Toy Story,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100731,100731,610,160341,2.5,Bloodmoon (1997),1997,Bloodmoon,0,1,0,...,0,0,0,0,0,0,0,1,0,0
100732,100732,610,160527,4.5,Sympathy for the Underdog (1971),1971,Sympathy for the Underdog,0,1,0,...,0,0,0,0,0,0,0,0,0,0
100733,100733,610,160836,3.0,Hazard (2005),2005,Hazard,0,1,0,...,0,0,0,0,0,0,0,1,0,0
100734,100734,610,163937,3.5,Blair Witch (2016),2016,Blair Witch,0,0,0,...,0,1,0,0,0,0,0,1,0,0
100735,100735,610,163981,3.5,31 (2016),2016,31,0,0,0,...,0,1,0,0,0,0,0,0,0,0

### Exercise: Your first recommender

Implement a recommender function that recommends the most popular movies to a user! Work with either the movie ids or the movie titles.

In [301]:
# list of movies a user has already rated / watched
list(ratings_extended[ratings_extended['userId'] == 1]['title'])

['Toy Story (1995)',
 'Grumpier Old Men (1995)',
 'Heat (1995)',
 'Seven (a.k.a. Se7en) (1995)',
 'Usual Suspects, The (1995)',
 'From Dusk Till Dawn (1996)',
 'Bottle Rocket (1996)',
 'Braveheart (1995)',
 'Rob Roy (1995)',
 'Canadian Bacon (1995)',
 'Desperado (1995)',
 'Billy Madison (1995)',
 'Clerks (1994)',
 'Dumb & Dumber (Dumb and Dumber) (1994)',
 'Ed Wood (1994)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Pulp Fiction (1994)',
 'Stargate (1994)',
 'Tommy Boy (1995)',
 'Clear and Present Danger (1994)',
 'Forrest Gump (1994)',
 'Jungle Book, The (1994)',
 'Mask, The (1994)',
 'Blown Away (1994)',
 'Dazed and Confused (1993)',
 'Fugitive, The (1993)',
 'Jurassic Park (1993)',
 'Mrs. Doubtfire (1993)',
 "Schindler's List (1993)",
 'So I Married an Axe Murderer (1993)',
 'Three Musketeers, The (1993)',
 'Tombstone (1993)',
 'Dances with Wolves (1990)',
 'Batman (1989)',
 'Silence of the Lambs, The (1991)',
 'Pinocchio (1940)',
 'Fargo (1996)',
 'Mission: Impossible (1996)',
 'James and the Giant Peach (1996)',
 'Space Jam (1996)',
 'Rock, The (1996)',
 'Twister (1996)',
 'Independence Day (a.k.a. ID4) (1996)',
 "She's the One (1996)",
 'Wizard of Oz, The (1939)',
 'Citizen Kane (1941)',
 'Adventures of Robin Hood, The (1938)',
 'Ghost and Mrs. Muir, The (1947)',
 'Mr. Smith Goes to Washington (1939)',
 'Escape to Witch Mountain (1975)',
 'Winnie the Pooh and the Blustery Day (1968)',
 'Three Caballeros, The (1945)',
 'Sword in the Stone, The (1963)',
 'Dumbo (1941)',
 "Pete's Dragon (1977)",
 'Bedknobs and Broomsticks (1971)',
 'Alice in Wonderland (1951)',
 'That Thing You Do! (1996)',
 'Ghost and the Darkness, The (1996)',
 'Swingers (1996)',
 'Willy Wonka & the Chocolate Factory (1971)',
 "Monty Python's Life of Brian (1979)",
 'Reservoir Dogs (1992)',
 'Platoon (1986)',
 'Basic Instinct (1992)',
 'E.T. the Extra-Terrestrial (1982)',
 'Abyss, The (1989)',
 'Monty Python and the Holy Grail (1975)',
 'Star Wars: Episode V - The Empire Strikes Back (1980)',
 'Princess Bride, The (1987)',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)',
 'Clockwork Orange, A (1971)',
 'Apocalypse Now (1979)',
 'Star Wars: Episode VI - Return of the Jedi (1983)',
 'Goodfellas (1990)',
 'Alien (1979)',
 'Psycho (1960)',
 'Blues Brothers, The (1980)',
 'Full Metal Jacket (1987)',
 'Henry V (1989)',
 'Quiet Man, The (1952)',
 'Terminator, The (1984)',
 'Duck Soup (1933)',
 'Shining, The (1980)',
 'Groundhog Day (1993)',
 'Back to the Future (1985)',
 'Highlander (1986)',
 'Young Frankenstein (1974)',
 'Fantasia (1940)',
 'Indiana Jones and the Last Crusade (1989)',
 'Pink Floyd: The Wall (1982)',
 'Nosferatu (Nosferatu, eine Symphonie des Grauens) (1922)',
 'Batman Returns (1992)',
 'Sneakers (1992)',
 'Last of the Mohicans, The (1992)',
 "McHale's Navy (1997)",
 'Best Men (1997)',
 'Grosse Pointe Blank (1997)',
 'Austin Powers: International Man of Mystery (1997)',
 'Con Air (1997)',
 'Face/Off (1997)',
 'Men in Black (a.k.a. MIB) (1997)',
 'Conan the Barbarian (1982)',
 'L.A. Confidential (1997)',
 'Kiss the Girls (1997)',
 'Game, The (1997)',
 'I Know What You Did Last Summer (1997)',
 'Starship Troopers (1997)',
 'Big Lebowski, The (1998)',
 'Wedding Singer, The (1998)',
 'Welcome to Woop-Woop (1997)',
 'Newton Boys, The (1998)',
 'Wild Things (1998)',
 'Small Soldiers (1998)',
 'All Quiet on the Western Front (1930)',
 'Rocky (1976)',
 'Labyrinth (1986)',
 'Lethal Weapon (1987)',
 'Goonies, The (1985)',
 'Back to the Future Part III (1990)',
 'Bambi (1942)',
 'Saving Private Ryan (1998)',
 'Black Cauldron, The (1985)',
 'Flight of the Navigator (1986)',
 'Great Mouse Detective, The (1986)',
 'Honey, I Shrunk the Kids (1989)',
 'Negotiator, The (1998)',
 'Jungle Book, The (1967)',
 'Rescuers, The (1977)',
 'Return to Oz (1985)',
 'Rocketeer, The (1991)',
 'Sleeping Beauty (1959)',
 'Song of the South (1946)',
 'Tron (1982)',
 'Indiana Jones and the Temple of Doom (1984)',
 'Lord of the Rings, The (1978)',
 "Charlotte's Web (1973)",
 'Secret of NIMH, The (1982)',
 'American Tail, An (1986)',
 'Legend (1985)',
 'NeverEnding Story, The (1984)',
 'Beetlejuice (1988)',
 'Willow (1988)',
 'Toys (1992)',
 'Few Good Men, A (1992)',
 'Rush Hour (1998)',
 'Edward Scissorhands (1990)',
 'American History X (1998)',
 'I Still Know What You Did Last Summer (1998)',
 'Enemy of the State (1998)',
 'King Kong (1933)',
 'Very Bad Things (1998)',
 'Psycho (1998)',
 'Rushmore (1998)',
 'Romancing the Stone (1984)',
 'Young Sherlock Holmes (1985)',
 'Thin Red Line, The (1998)',
 'Howard the Duck (1986)',
 'Texas Chainsaw Massacre, The (1974)',
 'Crocodile Dundee (1986)',
 '¡Three Amigos! (1986)',
 '20 Dates (1998)',
 'Office Space (1999)',
 "Logan's Run (1976)",
 'Planet of the Apes (1968)',
 'Lock, Stock & Two Smoking Barrels (1998)',
 'Matrix, The (1999)',
 'Go (1999)',
 'SLC Punk! (1998)',
 'Dick Tracy (1990)',
 'Mummy, The (1999)',
 'Star Wars: Episode I - The Phantom Menace (1999)',
 'Superman (1978)',
 'Superman II (1980)',
 'Dracula (1931)',
 'Frankenstein (1931)',
 'Wolf Man, The (1941)',
 'Rocky Horror Picture Show, The (1975)',
 'Run Lola Run (Lola rennt) (1998)',
 'South Park: Bigger, Longer and Uncut (1999)',
 'Ghostbusters (a.k.a. Ghost Busters) (1984)',
 'Iron Giant, The (1999)',
 'Big (1988)',
 '13th Warrior, The (1999)',
 'American Beauty (1999)',
 'Excalibur (1981)',
 "Gulliver's Travels (1939)",
 'Total Recall (1990)',
 'Dirty Dozen, The (1967)',
 'Goldfinger (1964)',
 'From Russia with Love (1963)',
 'Dr. No (1962)',
 'Fight Club (1999)',
 'RoboCop (1987)',
 'Who Framed Roger Rabbit? (1988)',
 'Live and Let Die (1973)',
 'Thunderball (1965)',
 'Being John Malkovich (1999)',
 'Spaceballs (1987)',
 'Robin Hood (1973)',
 'Dogma (1999)',
 'Messenger: The Story of Joan of Arc, The (1999)',
 'Longest Day, The (1962)',
 'Green Mile, The (1999)',
 'Easy Rider (1969)',
 'Talented Mr. Ripley, The (1999)',
 'Encino Man (1992)',
 'Sister Act (1992)',
 "Wayne's World (1992)",
 'Scream 3 (2000)',
 'JFK (1991)',
 'Teenage Mutant Ninja Turtles II: The Secret of the Ooze (1991)',
 'Teenage Mutant Ninja Turtles III (1993)',
 'Red Dawn (1984)',
 'Good Morning, Vietnam (1987)',
 'Grumpy Old Men (1993)',
 'Ladyhawke (1985)',
 'Hook (1991)',
 'Predator (1987)',
 'Gladiator (2000)',
 'Road Trip (2000)',
 'Man with the Golden Gun, The (1974)',
 'Blazing Saddles (1974)',
 'Mad Max (1979)',
 'Road Warrior, The (Mad Max 2) (1981)',
 'Shaft (1971)',
 'Big Trouble in Little China (1986)',
 'Shaft (2000)',
 'X-Men (2000)',
 'What About Bob? (1991)',
 'Transformers: The Movie (1986)',
 'M*A*S*H (a.k.a. MASH) (1970)']

In [302]:
ratings_aggregated = ratings_extended.groupby(['movieId','title'])                                   \
                               .agg(             { 'title':'size'         , 'rating':'mean'       }) \
                               .rename(columns = { 'title':'no_of_ratings', 'rating':'mean_rating'}) \
                               .reset_index()                                                        \
                               .sort_values(by = 'no_of_ratings', ascending = False) 

ratings_aggregated

,movieId,title,no_of_ratings,mean_rating
314,356,Forrest Gump (1994),329,4.164134
277,318,"Shawshank Redemption, The (1994)",317,4.429022
257,296,Pulp Fiction (1994),307,4.197068
510,593,"Silence of the Lambs, The (1991)",279,4.161290
1937,2571,"Matrix, The (1999)",278,4.192446
...,...,...,...,...
6682,58351,City of Men (Cidade dos Homens) (2007),1,4.000000
3043,4083,Best Seller (1987),1,4.000000
6686,58492,Snow Angels (2007),1,3.000000
6689,58627,Never Back Down (2008),1,3.500000
9718,193609,Andrew Dice Clay: Dice Rules (1991),1,4.000000

In [303]:
#type(ratings_pivot.mean())
ratings_pivot.mean().sort_values(ascending=False).index # [0]

Index(['Shawshank Redemption, The (1994)', 'Forrest Gump (1994)',
       'Pulp Fiction (1994)', 'Matrix, The (1999)',
       'Silence of the Lambs, The (1991)',
       'Star Wars: Episode IV - A New Hope (1977)', 'Fight Club (1999)',
       'Schindler's List (1993)',
       'Star Wars: Episode V - The Empire Strikes Back (1980)',
       'Usual Suspects, The (1995)',
       ...
       'Charlie's Angels (2000)', 'Waterworld (1995)',
       'Mission: Impossible II (2000)', 'Godzilla (1998)',
       'Nutty Professor, The (1996)', 'Batman & Robin (1997)',
       'Ace Ventura: When Nature Calls (1995)', 'Batman Forever (1995)',
       'Coneheads (1993)', 'Wild Wild West (1999)'],
      dtype='object', name='title', length=9719)

In [304]:
list_of_all = list(ratings_extended['title'].unique())
list_of_watch_user1 = list(ratings_extended[ratings_extended['userId'] == 1]['title'])
list_of_unpopular = list(ratings_aggregated[ratings_aggregated['no_of_ratings'] < 20]['title'])

In [305]:
recomm_baseline = set(list_of_all) - set(list_of_watch_user1) - set(list_of_unpopular)

recomm_baseline = list(recomm_baseline)

recomm_baseline

['Die Another Day (2002)',
 'Real Genius (1985)',
 'Robin Hood: Prince of Thieves (1991)',
 'Harold and Maude (1971)',
 'As Good as It Gets (1997)',
 'Up (2009)',
 'Spy Game (2001)',
 'Princess Mononoke (Mononoke-hime) (1997)',
 'Pineapple Express (2008)',
 'Beauty and the Beast (1991)',
 'River Runs Through It, A (1992)',
 'Million Dollar Baby (2004)',
 'Doctor Zhivago (1965)',
 'Fletch (1985)',
 'Life Aquatic with Steve Zissou, The (2004)',
 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)',
 'Beverly Hills Cop III (1994)',
 'Hurt Locker, The (2008)',
 'Saint, The (1997)',
 'Dolores Claiborne (1995)',
 "Dracula (Bram Stoker's Dracula) (1992)",
 'Town, The (2010)',
 "Emperor's New Groove, The (2000)",
 'Naked Gun: From the Files of Police Squad!, The (1988)',
 'Zootopia (2016)',
 "What's Eating Gilbert Grape (1993)",
 'Little Princess, A (1995)',
 'Gosford Park (2001)',
 'Ghost (1990)',
 'Risky Business (1983)',
 'Specialist, The (1994)',
 'Witness (1985)',
 'Hero (Ying xiong) (2002)',
 'Teenage Mutant Ninja Turtles (1990)',
 'Burn After Reading (2008)',
 'Planet of the Apes (2001)',
 'Gremlins (1984)',
 'Harry Potter and the Order of the Phoenix (2007)',
 'Notebook, The (2004)',
 'Honey, I Blew Up the Kid (1992)',
 'Birds, The (1963)',
 'Motorcycle Diaries, The (Diarios de motocicleta) (2004)',
 'Fisher King, The (1991)',
 'Little Miss Sunshine (2006)',
 'O Brother, Where Art Thou? (2000)',
 'Erin Brockovich (2000)',
 'Shrek the Third (2007)',
 'Ted (2012)',
 "Muriel's Wedding (1994)",
 'Batman & Robin (1997)',
 'Minority Report (2002)',
 'Mr. & Mrs. Smith (2005)',
 'Avatar (2009)',
 'Swordfish (2001)',
 'Three Colors: White (Trzy kolory: Bialy) (1994)',
 'Hercules (1997)',
 'Pitch Perfect (2012)',
 'Meet the Fockers (2004)',
 '28 Days (2000)',
 'Addams Family Values (1993)',
 'French Kiss (1995)',
 'Kill Bill: Vol. 1 (2003)',
 'U-571 (2000)',
 'Bedazzled (2000)',
 'Hoosiers (a.k.a. Best Shot) (1986)',
 'Training Day (2001)',
 'Notting Hill (1999)',
 'Mortal Kombat (1995)',
 'Peter Pan (1953)',
 'Lives of Others, The (Das leben der Anderen) (2006)',
 'Wrestler, The (2008)',
 'Click (2006)',
 'Night of the Living Dead (1968)',
 'Akira (1988)',
 'Forgetting Sarah Marshall (2008)',
 'The Hunger Games (2012)',
 'Hellboy (2004)',
 'Mission: Impossible III (2006)',
 'Some Like It Hot (1959)',
 'Hunchback of Notre Dame, The (1996)',
 'Ace Ventura: Pet Detective (1994)',
 'Big Hero 6 (2014)',
 'Robin Hood: Men in Tights (1993)',
 'Patch Adams (1998)',
 'I Am Legend (2007)',
 'Harry Potter and the Deathly Hallows: Part 2 (2011)',
 "Amores Perros (Love's a Bitch) (2000)",
 'Airplane! (1980)',
 'Mission to Mars (2000)',
 'River Wild, The (1994)',
 'Elf (2003)',
 'Phenomenon (1996)',
 'Shrek 2 (2004)',
 'Her (2013)',
 'Star Trek (2009)',
 'Deep Impact (1998)',
 'Entrapment (1999)',
 'Kiss Kiss Bang Bang (2005)',
 'Déjà Vu (Deja Vu) (2006)',
 'Virgin Suicides, The (1999)',
 "Howl's Moving Castle (Hauru no ugoku shiro) (2004)",
 'How the Grinch Stole Christmas (a.k.a. The Grinch) (2000)',
 'Air Force One (1997)',
 'Django Unchained (2012)',
 'For Your Eyes Only (1981)',
 'Nightmare Before Christmas, The (1993)',
 'Scrooged (1988)',
 'Jackie Brown (1997)',
 'Old School (2003)',
 'Star Wars: Episode VII - The Force Awakens (2015)',
 'My Cousin Vinny (1992)',
 'Spider-Man 2 (2004)',
 'Stranger than Fiction (2006)',
 'Sense and Sensibility (1995)',
 'Cinema Paradiso (Nuovo cinema Paradiso) (1989)',
 'Ghost World (2001)',
 'Brothers Grimm, The (2005)',
 'Hannibal (2001)',
 'Muppet Movie, The (1979)',
 'To Die For (1995)',
 'When Harry Met Sally... (1989)',
 '(500) Days of Summer (2009)',
 'Karate Kid, Part II, The (1986)',
 "Singin' in the Rain (1952)",
 'Right Stuff, The (1983)',
 'North by Northwest (1959)',
 'Third Man, The (1949)',
 'Others, The (2001)',
 'Father of the Bride Part II (1995)',
 'Other Guys, The (2010)',
 'Rocky IV (1985)',
 'Lethal Weapon 4 (1998)',
 'Kingsman: The Secret Service (2015)',
 'Dirty Dancing (1987)',
 'The Imitation Game (2014)',
 'Judge Dredd (1995)',
 "My Best Friend's Wedding (1997)",
 'Gravity (2013)',
 'Fast and the Furious, The (2001)',
 "We're the Millers (2013)",
 'Terminator 2: Judgment Day (1991)',
 'Godzilla (1998)',
 'Tarzan (1999)',
 'The Lego Movie (2014)',
 'Life Is Beautiful (La Vita è bella) (1997)',
 'Prince of Egypt, The (1998)',
 'Interview with the Vampire: The Vampire Chronicles (1994)',
 'Nausicaä of the Valley of the Wind (Kaze no tani no Naushika) (1984)',
 'Garden State (2004)',
 'George of the Jungle (1997)',
 'Bourne Identity, The (2002)',
 'National Treasure (2004)',
 'Firm, The (1993)',
 "Charlie's Angels: Full Throttle (2003)",
 "Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)",
 'X2: X-Men United (2003)',
 'World Is Not Enough, The (1999)',
 '12 Angry Men (1957)',
 "Boys Don't Cry (1999)",
 'Adjustment Bureau, The (2011)',
 "All the President's Men (1976)",
 'Dancer in the Dark (2000)',
 'Mars Attacks! (1996)',
 'High Fidelity (2000)',
 'Streetcar Named Desire, A (1951)',
 'I.Q. (1994)',
 'Walk in the Clouds, A (1995)',
 'First Blood (Rambo: First Blood) (1982)',
 'Untouchables, The (1987)',
 'City of Lost Children, The (Cité des enfants perdus, La) (1995)',
 'Mystery Men (1999)',
 'Graduate, The (1967)',
 'Despicable Me (2010)',
 'Working Girl (1988)',
 'Sandlot, The (1993)',
 'Heavy Metal (1981)',
 'X-Files: Fight the Future, The (1998)',
 "It's a Wonderful Life (1946)",
 'Dead Man Walking (1995)',
 'Deep Blue Sea (1999)',
 'Bourne Supremacy, The (2004)',
 'Strangers on a Train (1951)',
 'Fifth Element, The (1997)',
 'Madagascar (2005)',
 'Fantastic Four: Rise of the Silver Surfer (2007)',
 'Sixteen Candles (1984)',
 "Bug's Life, A (1998)",
 'Congo (1995)',
 'Avengers: Age of Ultron (2015)',
 'Daredevil (2003)',
 'Harry Potter and the Half-Blood Prince (2009)',
 'Dragonheart (1996)',
 'Iron Man 3 (2013)',
 'Star Trek: Insurrection (1998)',
 'Caddyshack (1980)',
 'Pursuit of Happyness, The (2006)',
 'Pretty in Pink (1986)',
 'Predator 2 (1990)',
 'Bridget Jones: The Edge of Reason (2004)',
 'Crimson Tide (1995)',
 'Shallow Hal (2001)',
 'Down Periscope (1996)',
 'Mask of Zorro, The (1998)',
 '6th Day, The (2000)',
 'Snowpiercer (2013)',
 'Rumble in the Bronx (Hont faan kui) (1995)',
 'Guardians of the Galaxy (2014)',
 'Seven Samurai (Shichinin no samurai) (1954)',
 'Meet the Parents (2000)',
 'Short Circuit (1986)',
 'Patton (1970)',
 "Pan's Labyrinth (Laberinto del fauno, El) (2006)",
 'Children of Men (2006)',
 'Scary Movie 3 (2003)',
 'Speed (1994)',
 'Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)',
 'Anchorman: The Legend of Ron Burgundy (2004)',
 'K-PAX (2001)',
 'Live Free or Die Hard (2007)',
 'House of Flying Daggers (Shi mian mai fu) (2004)',
 'Home Alone 2: Lost in New York (1992)',
 'Chinatown (1974)',
 'Fahrenheit 9/11 (2004)',
 'Cape Fear (1991)',
 'Dawn of the Dead (1978)',
 'Big Fish (2003)',
 'Heavenly Creatures (1994)',
 'Sleepless in Seattle (1993)',
 'Omen, The (1976)',
 'Little Nicky (2000)',
 'Stripes (1981)',
 'Cliffhanger (1993)',
 'Notorious (1946)',
 '101 Dalmatians (1996)',
 'Silver Linings Playbook (2012)',
 'Beautiful Mind, A (2001)',
 "National Lampoon's Van Wilder (2002)",
 'Last Emperor, The (1987)',
 "Jacob's Ladder (1990)",
 'Craft, The (1996)',
 'Aladdin (1992)',
 'Mad Max: Fury Road (2015)',
 'Say Anything... (1989)',
 'Departed, The (2006)',
 'Whole Nine Yards, The (2000)',
 'Midnight Run (1988)',
 'Casino (1995)',
 'Repo Man (1984)',
 'Curious Case of Benjamin Button, The (2008)',
 'Ace Ventura: When Nature Calls (1995)',
 'Metropolis (1927)',
 'Blind Side, The  (2009)',
 'To Catch a Thief (1955)',
 "Monty Python's And Now for Something Completely Different (1971)",
 'Frequency (2000)',
 'Lara Croft: Tomb Raider (2001)',
 'Stardust (2007)',
 'Donnie Darko (2001)',
 'Broken Flowers (2005)',
 'Mighty Ducks, The (1992)',
 'Magnolia (1999)',
 'Resident Evil (2002)',
 'Dangerous Liaisons (1988)',
 'Barb Wire (1996)',
 '27 Dresses (2008)',
 'Final Destination (2000)',
 'Perks of Being a Wallflower, The (2012)',
 'Alien³ (a.k.a. Alien 3) (1992)',
 'Anaconda (1997)',
 'Three Colors: Blue (Trois couleurs: Bleu) (1993)',
 'Casper (1995)',
 'Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The (2005)',
 "National Lampoon's Vacation (1983)",
 'Good bye, Lenin! (2003)',
 'Star Trek III: The Search for Spock (1984)',
 'Wolf of Wall Street, The (2013)',
 'Die Hard: With a Vengeance (1995)',
 'Contact (1997)',
 'Godfather: Part II, The (1974)',
 'Downfall (Untergang, Der) (2004)',
 'Argo (2012)',
 'Little Big Man (1970)',
 'American Psycho (2000)',
 'Cool Hand Luke (1967)',
 'Midnight Cowboy (1969)',
 'Captain America: The First Avenger (2011)',
 'Simple Plan, A (1998)',
 'Terms of Endearment (1983)',
 'Karate Kid, The (1984)',
 'Stand by Me (1986)',
 'Young Guns (1988)',
 'Event Horizon (1997)',
 'Tootsie (1982)',
 'Fistful of Dollars, A (Per un pugno di dollari) (1964)',
 "William Shakespeare's Romeo + Juliet (1996)",
 "Weekend at Bernie's (1989)",
 'Ratatouille (2007)',
 'Conspiracy Theory (1997)',
 'The Butterfly Effect (2004)',
 'Crying Game, The (1992)',
 'Iron Man (2008)',
 'Bone Collector, The (1999)',
 "Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)",
 'Blade II (2002)',
 'Keeping the Faith (2000)',
 'Running Man, The (1987)',
 'The Hunger Games: Mockingjay - Part 1 (2014)',
 'Happy Gilmore (1996)',
 'Evil Dead II (Dead by Dawn) (1987)',
 'Moonraker (1979)',
 'Grand Day Out with Wallace and Gromit, A (1989)',
 'And Your Mother Too (Y tu mamá también) (2001)',
 'eXistenZ (1999)',
 "There's Something About Mary (1998)",
 'Miracle on 34th Street (1994)',
 'Fear and Loathing in Las Vegas (1998)',
 'Wedding Crashers (2005)',
 '8 Mile (2002)',
 'Captain Phillips (2013)',
 'Bull Durham (1988)',
 'Doors, The (1991)',
 "Miller's Crossing (1990)",
 'French Connection, The (1971)',
 'In Bruges (2008)',
 'Ring, The (2002)',
 'Kick-Ass (2010)',
 'Pearl Harbor (2001)',
 'Hot Shots! Part Deux (1993)',
 'Sabrina (1995)',
 'Bio-Dome (1996)',
 'Nell (1994)',
 "Bridget Jones's Diary (2001)",
 'Lost Boys, The (1987)',
 'Princess Diaries, The (2001)',
 'Captain America: Civil War (2016)',
 'Friday (1995)',
 'Traffic (2000)',
 'Major League (1989)',
 'X-Men: Days of Future Past (2014)',
 'Patriot, The (2000)',
 'Home Alone (1990)',
 'Island, The (2005)',
 'Punch-Drunk Love (2002)',
 'Election (1999)',
 '28 Days Later (2002)',
 'Awakenings (1990)',
 'Men in Black II (a.k.a. MIIB) (a.k.a. MIB 2) (2002)',
 'Hancock (2008)',
 'Lord of the Rings: The Fellowship of the Ring, The (2001)',
 'Black Swan (2010)',
 'Rush Hour 2 (2001)',
 'Finding Nemo (2003)',
 "She's All That (1999)",
 'Italian Job, The (2003)',
 'Jurassic World (2015)',
 'Road to Perdition (2002)',
 'Aristocats, The (1970)',
 'Godfather: Part III, The (1990)',
 'Legends of the Fall (1994)',
 'Michael (1996)',
 'Identity (2003)',
 "White Men Can't Jump (1992)",
 'Mighty Aphrodite (1995)',
 'Close Encounters of the Third Kind (1977)',
 'Megamind (2010)',
 'Pretty Woman (1990)',
 'Pride & Prejudice (2005)',
 'Matrix Revolutions, The (2003)',
 'Man in the Iron Mask, The (1998)',
 '21 Jump Street (2012)',
 'Moonrise Kingdom (2012)',
 'G.I. Jane (1997)',
 'Lost in Translation (2003)',
 'Under Siege 2: Dark Territory (1995)',
 'Roger & Me (1989)',
 'Bowling for Columbine (2002)',
 'Coneheads (1993)',
 'Philadelphia Story, The (1940)',
 'Executive Decision (1996)',
 'Thelma & Louise (1991)',
 'Amadeus (1984)',
 "Ocean's Eleven (2001)",
 'Almost Famous (2000)',
 'Quiz Show (1994)',
 'Flintstones, The (1994)',
 'Fantastic Four (2005)',
 'Blade (1998)',
 'Gandhi (1982)',
 'Arsenic and Old Lace (1944)',
 'Wreck-It Ralph (2012)',
 "Christmas Vacation (National Lampoon's Christmas Vacation) (1989)",
 'Triplets of Belleville, The (Les triplettes de Belleville) (2003)',
 'Junior (1994)',
 'Austin Powers in Goldmember (2002)',
 'Toy Story 2 (1999)',
 'Mexican, The (2001)',
 'Terminal, The (2004)',
 'Primal Fear (1996)',
 "Charlie's Angels (2000)",
 'Casino Royale (2006)',
 'Bruce Almighty (2003)',
 "Carlito's Way (1993)",
 'Master and Commander: The Far Side of the World (2003)',
 'Crazy, Stupid, Love. (2011)',
 'Last Action Hero (1993)',
 "Pee-wee's Big Adventure (1985)",
 'Donnie Brasco (1997)',
 'Gone Baby Gone (2007)',
 'Rounders (1998)',
 'Nine Months (1995)',
 '101 Dalmatians (One Hundred and One Dalmatians) (1961)',
 'Sleepers (1996)',
 'Zodiac (2007)',
 'Harry Potter and the Prisoner of Azkaban (2004)',
 'Behind Enemy Lines (2001)',
 'Manchurian Candidate, The (1962)',
 '25th Hour (2002)',
 'Forget Paris (1995)',
 'Harry Potter and the Goblet of Fire (2005)',
 'Fatal Attraction (1987)',
 'WALL·E (2008)',
 'Apartment, The (1960)',
 'xXx (2002)',
 'American Pie 2 (2001)',
 'X-Men Origins: Wolverine (2009)',
 'Blow (2001)',
 'Galaxy Quest (1999)',
 'People vs. Larry Flynt, The (1996)',
 'Arlington Road (1999)',
 'V for Vendetta (2006)',
 'Birdcage, The (1996)',
 'In the Line of Fire (1993)',
 'Full Monty, The (1997)',
 'Sixth Sense, The (1999)',
 'Strictly Ballroom (1992)',
 'Much Ado About Nothing (1993)',
 'Clueless (1995)',
 'Finding Forrester (2000)',
 'In the Name of the Father (1993)',
 'History of Violence, A (2005)',
 "Dr. Horrible's Sing-Along Blog (2008)",
 'Bourne Ultimatum, The (2007)',
 'Indiana Jones and the Kingdom of the Crystal Skull (2008)',
 'Tangled (2010)',
 'Boiler Room (2000)',
 'Dark Knight, The (2008)',
 'Searching for Bobby Fischer (1993)',
 'Taxi Driver (1976)',
 'Red (2010)',
 'Spider-Man 3 (2007)',
 'Lawrence of Arabia (1962)',
 'Apollo 13 (1995)',
 'Roman Holiday (1953)',
 'Batman Begins (2005)',
 'Scott Pilgrim vs. the World (2010)',
 'Ice Age (2002)',
 'Catch Me If You Can (2002)',
 'Showgirls (1995)',
 'Fox and the Hound, The (1981)',
 'Alien: Resurrection (1997)',
 'Matilda (1996)',
 'Star Wars: Episode II - Attack of the Clones (2002)',
 'Chasing Amy (1997)',
 'American President, The (1995)',
 'Signs (2002)',
 'Coyote Ugly (2000)',
 'American Werewolf in London, An (1981)',
 'Beverly Hillbillies, The (1993)',
 'John Wick (2014)',
 'Bound (1996)',
 'Animal House (1978)',
 'Tropic Thunder (2008)',
 'Enemy at the Gates (2001)',
 'Bullets Over Broadway (1994)',
 'Crocodile Dundee II (1988)',
 'Dirty Harry (1971)',
 'Sliding Doors (1998)',
 'Unbreakable (2000)',
 'Easy A (2010)',
 'On the Waterfront (1954)',
 'Maltese Falcon, The (1941)',
 'Cable Guy, The (1996)',
 'Dune (1984)',
 "One Flew Over the Cuckoo's Nest (1975)",
 'Time Machine, The (2002)',
 'Moonstruck (1987)',
 'Incredible Hulk, The (2008)',
 'Wallace & Gromit in The Curse of the Were-Rabbit (2005)',
 'Nightmare on Elm Street, A (1984)',
 'Licence to Kill (1989)',
 'Timecop (1994)',
 'Net, The (1995)',
 'Man on the Moon (1999)',
 'Limitless (2011)',
 "Bill & Ted's Excellent Adventure (1989)",
 'King Kong (2005)',
 'Gattaca (1997)',
 'Broadcast News (1987)',
 'Corpse Bride (2005)',
 'Faculty, The (1998)',
 'Shooter (2007)',
 'Little Mermaid, The (1989)',
 'Scent of a Woman (1992)',
 'Holiday, The (2006)',
 'Anastasia (1997)',
 'Heathers (1989)',
 'Girl, Interrupted (1999)',
 'Spy Hard (1996)',
 'Deadpool (2016)',
 'Modern Times (1936)',
 'Inglourious Basterds (2009)',
 "Bill & Ted's Bogus Journey (1991)",
 'Dog Day Afternoon (1975)',
 'Nutty Professor, The (1996)',
 'City Slickers (1991)',
 'Bridge on the River Kwai, The (1957)',
 'Vertigo (1958)',
 'WarGames (1983)',
 'Maverick (1994)',
 'Pay It Forward (2000)',
 "Ferris Bueller's Day Off (1986)",
 'Whiplash (2014)',
 'Lord of War (2005)',
 'Remember the Titans (2000)',
 'Spawn (1997)',
 'Arrival, The (1996)',
 'Striptease (1996)',
 'Insider, The (1999)',
 'Star Trek II: The Wrath of Khan (1982)',
 'Welcome to the Dollhouse (1995)',
 'Shutter Island (2010)',
 'The Revenant (2015)',
 'Blood Diamond (2006)',
 'Knocked Up (2007)',
 'Good, the Bad and the Ugly, The (Buono, il brutto, il cattivo, Il) (1966)',
 'Rain Man (1988)',
 'Jaws (1975)',
 'Toy Story 3 (2010)',
 'Rise of the Planet of the Apes (2011)',
 'Time to Kill, A (1996)',
 'Tin Cup (1996)',
 'Elizabeth (1998)',
 'I, Robot (2004)',
 'Bad Boys (1995)',
 'About Schmidt (2002)',
 'Blast from the Past (1999)',
 'Coming to America (1988)',
 "City Slickers II: The Legend of Curly's Gold (1994)",
 'Interstellar (2014)',
 'Producers, The (1968)',
 'Team America: World Police (2004)',
 'Animatrix, The (2003)',
 'True Lies (1994)',
 'Adaptation (2002)',
 'Outbreak (1995)',
 'Gone Girl (2014)',
 'The Martian (2015)',
 'Panic Room (2002)',
 'Jurassic Park III (2001)',
 'In & Out (1997)',
 'Armageddon (1998)',
 'Hobbit: The Desolation of Smaug, The (2013)',
 'Deer Hunter, The (1978)',
 'Little Shop of Horrors (1986)',
 'Joe Dirt (2001)',
 "Dante's Peak (1997)",
 'Sling Blade (1996)',
 'Collateral (2004)',
 'Cube (1997)',
 'Coraline (2009)',
 'Jewel of the Nile, The (1985)',
 'Bridges of Madison County, The (1995)',
 'Casablanca (1942)',
 'Battle Royale (Batoru rowaiaru) (2000)',
 'Airheads (1994)',
 'What Women Want (2000)',
 'Devil Wears Prada, The (2006)',
 'Lethal Weapon 3 (1992)',
 'Postman, The (Postino, Il) (1994)',
 'Fighter, The (2010)',
 'Mary Poppins (1964)',
 'Taken (2008)',
 'Sex, Lies, and Videotape (1989)',
 'Big Chill, The (1983)',
 'Weird Science (1985)',
 'Don Juan DeMarco (1995)',
 'Dodgeball: A True Underdog Story (2004)',
 'Sgt. Bilko (1996)',
 'Village, The (2004)',
 'Ghostbusters II (1989)',
 'Evil Dead, The (1981)',
 'Great Escape, The (1963)',
 'Chicago (2002)',
 'Midnight in the Garden of Good and Evil (1997)',
 'Paper, The (1994)',
 'Star Trek V: The Final Frontier (1989)',
 'Big Short, The (2015)',
 'My Neighbor Totoro (Tonari no Totoro) (1988)',
 'Eraser (1996)',
 'Munich (2005)',
 'No Country for Old Men (2007)',
 'To Wong Foo, Thanks for Everything! Julie Newmar (1995)',
 'Troy (2004)',
 'Starsky & Hutch (2004)',
 'Buffy the Vampire Slayer (1992)',
 'Top Gun (1986)',
 'Thor: Ragnarok (2017)',
 'Perfect Storm, The (2000)',
 'Aeon Flux (2005)',
 'Sabrina (1954)',
 '40-Year-Old Virgin, The (2005)',
 'Jerk, The (1979)',
 '13 Going on 30 (2004)',
 'Stigmata (1999)',
 'Boondock Saints, The (2000)',
 "Mary Shelley's Frankenstein (Frankenstein) (1994)",
 'Pocahontas (1995)',
 'English Patient, The (1996)',
 'Secret Garden, The (1993)',
 'Desperately Seeking Susan (1985)',
 'Life of Pi (2012)',
 'Scary Movie (2000)',
 'Inspector Gadget (1999)',
 'American Graffiti (1973)',
 'View to a Kill, A (1985)',
 'Girl Next Door, The (2004)',
 'This Is Spinal Tap (1984)',
 'Now You See Me (2013)',
 'Driving Miss Daisy (1989)',
 'Reality Bites (1994)',
 'Grand Budapest Hotel, The (2014)',
 'Naked Gun 33 1/3: The Final Insult (1994)',
 "Hitchhiker's Guide to the Galaxy, The (2005)",
 'Titanic (1997)',
 'Up in the Air (2009)',
 'Bend It Like Beckham (2002)',
 'Lilo & Stitch (2002)',
 'Ice Age 2: The Meltdown (2006)',
 'Zack and Miri Make a Porno (2008)',
 'RoboCop 2 (1990)',
 'Ben-Hur (1959)',
 'Cabin in the Woods, The (2012)',
 'Strange Days (1995)',
 'Sin City (2005)',
 'Crow, The (1994)',
 'True Grit (2010)',
 'Killing Fields, The (1984)',
 'Leaving Las Vegas (1995)',
 'Gods Must Be Crazy, The (1980)',
 'Fried Green Tomatoes (1991)',
 'Napoleon Dynamite (2004)',
 'Kill Bill: Vol. 2 (2004)',
 'Freaky Friday (2003)',
 'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)',
 'Hollow Man (2000)',
 'Mystery Science Theater 3000: The Movie (1996)',
 'I Heart Huckabees (2004)',
 'Dead Poets Society (1989)',
 'Guardians of the Galaxy 2 (2017)',
 'Evolution (2001)',
 'Darjeeling Limited, The (2007)',
 'Player, The (1992)',
 'Under Siege (1992)',
 'Bridesmaids (2011)',
 'Ever After: A Cinderella Story (1998)',
 'The Scorpion King (2002)',
 'How to Lose a Guy in 10 Days (2003)',
 'Superbad (2007)',
 'Sting, The (1973)',
 'Analyze This (1999)',
 'Time Bandits (1981)',
 'Exorcist, The (1973)',
 'Fish Called Wanda, A (1988)',
 'RoboCop 3 (1993)',
 'Mad Max Beyond Thunderdome (1985)',
 'Intouchables (2011)',
 'Secret Life of Walter Mitty, The (2013)',

In [306]:
# we need to read the following preprocessed dataframes:
#              - ratings_extended
#              - ratings_aggregated


# collaborative filtering = look at ratings only!
def recommend_popular(query, ratings, k=10):
    """
    Filters and recommends the top k movies for any given input query. 
    Returns a list of k movie ids.
    """
    # 1. candidate generation
    
    # list of all movies
    list_of_all = list(ratings_extended['title'].unique())
    # filter out movies that the user has already seen
    list_of_watch_user1 = list(ratings_extended[ratings_extended['userId'] == 1]['title'])
    # filter out movies that have been watched by less than 20/50/100... users
    list_of_unpopular = list(ratings_aggregated[ratings_aggregated['no_of_ratings'] < 20]['title'])
    
    recomm_baseline = set(list_of_all) - set(list_of_watch_user1) - set(list_of_unpopular)

    recomm_baseline = list(recomm_baseline)

    recomm_baseline
    # 2. scoring
    
    # calculate the average rating for each movie
    
    
    # 3. ranking
    
    # return the top-k highest rated movie ids or titles

In [307]:
type(recomm_baseline)

list

### Export 2

In [308]:
ratings_aggregated

,movieId,title,no_of_ratings,mean_rating
314,356,Forrest Gump (1994),329,4.164134
277,318,"Shawshank Redemption, The (1994)",317,4.429022
257,296,Pulp Fiction (1994),307,4.197068
510,593,"Silence of the Lambs, The (1991)",279,4.161290
1937,2571,"Matrix, The (1999)",278,4.192446
...,...,...,...,...
6682,58351,City of Men (Cidade dos Homens) (2007),1,4.000000
3043,4083,Best Seller (1987),1,4.000000
6686,58492,Snow Angels (2007),1,3.000000
6689,58627,Never Back Down (2008),1,3.500000
9718,193609,Andrew Dice Clay: Dice Rules (1991),1,4.000000

### Non-negative matrix factorization (NMF)

In [309]:
import numpy as np
from sklearn.decomposition import NMF 
import pandas as pd

In [310]:
ratings_pivot

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,4.000000,3.262335
2,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
3,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
4,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
5,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
607,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
608,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,4.500000,3.500000,3.262335,3.262335,3.262335
609,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,...,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335
610,4.000000,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.262335,3.500000,3.262335,...,3.262335,4.000000,3.500000,3.000000,3.262335,3.262335,2.000000,1.500000,3.262335,3.262335

In [311]:
nmf_model = NMF(n_components=20, max_iter=500)

In [312]:
nmf_model.fit(ratings_pivot)

/home/florianriemann/anaconda3/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:289: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(
/home/florianriemann/anaconda3/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:1637: ConvergenceWarning: Maximum number of iterations 500 reached. Increase it to improve convergence.
  warnings.warn(

NMF(max_iter=500, n_components=20)

In [313]:
Q_matrix = nmf_model.components_

In [314]:
Q_matrix.shape

(20, 9719)

In [315]:
Q_matrix

array([[0.85958294, 0.86122635, 0.86304643, ..., 0.86393258, 0.82447219,
        0.86673447],
       [0.02146373, 0.01800108, 0.01810758, ..., 0.00813497, 0.01150859,
        0.01722675],
       [0.31790859, 0.44815705, 0.41979595, ..., 0.58104175, 0.51341998,
        0.43906324],
       ...,
       [0.10833704, 0.1059233 , 0.09895692, ..., 0.10979158, 0.20649804,
        0.11716731],
       [0.07754334, 0.1010736 , 0.10109469, ..., 0.15776251, 0.11040269,
        0.10520966],
       [0.09482519, 0.06670543, 0.06746902, ..., 0.        , 0.12490297,
        0.06861422]])

In [316]:
nmf_model.feature_names_in_

array(["'71 (2014)", "'Hellboy': The Seeds of Creation (2004)",
       "'Round Midnight (1986)", ..., 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)',
       'À nous la liberté (Freedom for Us) (1931)'], dtype=object)

In [317]:
Q = pd.DataFrame(data=Q_matrix,
            columns=nmf_model.feature_names_in_)

In [318]:
Q

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
0,0.859583,0.861226,0.863046,0.866834,0.866213,0.863888,0.808376,0.865623,0.817461,0.862016,...,0.861670,0.844381,0.861310,0.866453,0.862468,0.839546,0.863927,0.863933,0.824472,0.866734
1,0.021464,0.018001,0.018108,0.018067,0.018122,0.018807,0.018488,0.018150,0.012667,0.012906,...,0.005534,0.022721,0.018761,0.016716,0.018194,0.018587,0.000000,0.008135,0.011509,0.017227
2,0.317909,0.448157,0.419796,0.379335,0.388559,0.375019,0.146693,0.404631,1.793260,0.435808,...,0.243954,0.103785,0.439388,0.489511,0.420760,0.634020,0.340752,0.581042,0.513420,0.439063
3,0.046860,0.054321,0.054283,0.054488,0.054283,0.052961,0.064437,0.055171,0.022426,0.036785,...,0.018827,0.044638,0.052327,0.057172,0.053987,0.044362,0.013646,0.075210,0.064253,0.055896
4,0.126550,0.151097,0.144356,0.135956,0.132872,0.138373,0.128902,0.134094,0.088350,0.143882,...,0.130446,0.133568,0.131506,0.140197,0.142954,0.000000,0.216147,0.210262,0.148193,0.093123
5,0.180186,0.145860,0.143541,0.138477,0.144886,0.041797,0.981072,0.130268,0.000000,0.140248,...,0.187722,0.480966,0.094538,0.079673,0.145917,0.086909,0.144588,0.272570,0.620916,0.000000
6,0.107313,0.092334,0.092435,0.091281,0.091823,0.094208,0.137364,0.097241,0.056959,0.122539,...,0.140788,0.101399,0.096359,0.087659,0.092996,0.091593,0.119227,0.049704,0.086840,0.088786
7,0.048775,0.048854,0.049086,0.049126,0.049156,0.049855,0.040456,0.049347,0.075736,0.050978,...,0.052939,0.046569,0.049792,0.049802,0.049058,0.073226,0.044030,0.049742,0.041397,0.051641
8,0.040798,0.041018,0.041036,0.041236,0.041151,0.040541,0.007477,0.037357,0.027419,0.046685,...,0.061695,0.041284,0.040352,0.041017,0.041152,0.053887,0.068440,0.040400,0.028608,0.040372
9,0.060698,0.065748,0.065660,0.065762,0.065660,0.064497,0.029356,0.066053,0.084167,0.069212,...,0.071110,0.126607,0.053229,0.058107,0.065442,0.076340,0.057223,0.066946,0.057377,0.065430
10,0.281678,0.180917,0.176374,0.175478,0.175324,0.237973,0.192658,0.150782,0.232674,0.190585,...,0.261049,0.474618,0.226283,0.109542,0.167506,0.329500,0.193772,0.000000,0.146753,0.213519
11,0.180493,0.227959,0.209173,0.165091,0.166712,0.294838,0.529207,0.192182,0.701961,0.182325,...,0.194008,0.122125,0.312610,0.249588,0.222183,0.725580,0.132194,0.000000,0.443207,0.283240
12,0.118838,0.122721,0.122214,0.123101,0.123143,0.124906,0.134354,0.116780,0.249400,0.138199,...,0.130941,0.093518,0.122121,0.127747,0.121708,0.068688,0.130324,0.133403,0.143995,0.106341
13,0.052768,0.056447,0.056528,0.056713,0.056644,0.056420,0.021262,0.057576,0.038247,0.051741,...,0.059373,0.046153,0.055887,0.058825,0.056550,0.035672,0.063549,0.064444,0.035670,0.057844
14,0.096555,0.092311,0.092774,0.093372,0.093335,0.094804,0.000000,0.082420,0.077656,0.078768,...,0.050702,0.103804,0.094138,0.090600,0.092784,0.127382,0.033866,0.089222,0.085076,0.097077
15,0.081835,0.084697,0.085389,0.085950,0.086072,0.085958,0.080591,0.087700,0.045362,0.085409,...,0.089099,0.087995,0.085053,0.086067,0.085626,0.148691,0.109067,0.093480,0.096815,0.085581
16,0.055036,0.053957,0.053776,0.054023,0.054040,0.054346,0.072905,0.053748,0.045823,0.050226,...,0.046703,0.032339,0.058519,0.056492,0.053839,0.097006,0.052982,0.054193,0.057298,0.054352
17,0.108337,0.105923,0.098957,0.091850,0.092006,0.112390,0.280565,0.091141,0.249966,0.138473,...,0.148448,0.116510,0.099225,0.093238,0.099864,0.234926,0.167388,0.109792,0.206498,0.117167
18,0.077543,0.101074,0.101095,0.100479,0.100178,0.092743,0.235646,0.112410,0.198994,0.089922,...,0.119587,0.072543,0.097544,0.111690,0.100692,0.070358,0.156000,0.157763,0.110403,0.105210
19,0.094825,0.066705,0.067469,0.066949,0.066627,0.055792,0.091976,0.067372,0.161669,0.069507,...,0.067782,0.076387,0.076736,0.060614,0.067634,0.042519,0.004026,0.000000,0.124903,0.068614

In [319]:
nmf_model.transform(ratings_pivot).shape

(610, 20)

In [320]:
P_matrix = nmf_model.transform(ratings_pivot)
P_matrix

array([[ 3.11733544,  6.46508953,  0.08976198, ...,  0.18149685,
         0.25727793,  0.        ],
       [ 3.43834435,  0.58679762,  0.07587432, ...,  0.13844578,
         0.21764036,  0.37504332],
       [ 3.48644239,  1.38022182,  0.06875931, ...,  0.10657019,
         0.        ,  0.26095816],
       ...,
       [ 1.55085428,  9.67159227,  0.33885651, ...,  0.17167656,
         0.        ,  0.        ],
       [ 3.48059444,  0.60540467,  0.06848778, ...,  0.16448667,
         0.11111028,  0.15690743],
       [ 1.89177116, 23.08692913,  0.        , ...,  0.        ,
         0.        ,  5.88342531]])

In [321]:
pd.DataFrame(data = P_matrix, index = ratings_pivot.index)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
userId,,,,,,,,,,,,,,,,,,,,
1,3.117335,6.465090,0.089762,0.881400,0.287080,0.276950,1.410828,0.614403,0.000000,0.010824,0.042650,0.068479,0.300160,0.185568,0.000000,0.309984,0.000000,0.181497,0.257278,0.000000
2,3.438344,0.586798,0.075874,0.294634,0.067088,0.170430,0.146103,0.147468,0.143444,0.055966,0.152408,0.073853,0.128382,0.220077,0.116177,0.166723,0.296457,0.138446,0.217640,0.375043
3,3.486442,1.380222,0.068759,0.071126,0.047370,0.192841,0.181165,0.312681,0.215448,0.264710,0.150776,0.045062,0.000000,0.163513,0.000000,0.000000,0.559467,0.106570,0.000000,0.260958
4,3.303792,1.316245,0.044553,0.333837,0.332885,0.156818,0.088904,0.049083,0.565882,0.288406,0.055903,0.000000,0.520932,0.091620,0.038082,0.000000,0.942200,0.148831,0.350855,0.718023
5,3.459644,0.513364,0.057615,0.148087,0.103696,0.179178,0.134878,0.184591,0.279848,0.307805,0.090387,0.113479,0.068211,0.247953,0.267540,0.001649,0.342539,0.152764,0.160967,0.080744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.830970,0.741522,0.156075,2.569186,0.249061,0.000000,0.056963,0.000000,2.373908,1.304872,0.001590,0.033127,0.740815,1.322954,0.636959,0.272154,0.693756,1.103118,0.000000,0.000000
607,3.369173,0.577795,0.041230,0.178951,0.145372,0.221257,0.358456,0.614437,0.165997,0.337519,0.089850,0.197701,0.241812,0.000000,0.000000,0.542520,0.747311,0.000000,0.015803,0.000000
608,1.550854,9.671592,0.338857,0.000000,0.000000,0.000000,0.000000,2.790909,7.523261,1.168536,0.140191,0.178665,0.000000,3.539311,0.011255,9.675067,0.000000,0.171677,0.000000,0.000000
609,3.480594,0.605405,0.068488,0.158207,0.087143,0.175879,0.060806,0.184717,0.193146,0.206711,0.107014,0.091048,0.094893,0.160736,0.041091,0.210292,0.337085,0.164487,0.111110,0.156907
610,1.891771,23.086929,0.000000,0.000000,0.000000,0.062871,5.000505,0.264575,0.450132,0.539468,0.766226,0.000000,0.028345,0.000000,1.506886,0.000000,0.000000,0.000000,0.000000,5.883425

In [322]:
P_matrix.shape, Q_matrix.shape

((610, 20), (20, 9719))

In [323]:
R_hat_matrix = np.dot(P_matrix,Q_matrix)

In [324]:
R_hat_matrix.shape

(610, 9719)

In [325]:
R_hat = pd.DataFrame(data    = R_hat_matrix,
                     columns = nmf_model.feature_names_in_,
                     index   = ratings_pivot.index)

In [326]:
R_hat

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,3.291286,3.276105,3.274932,3.273579,3.274412,3.259710,3.462414,3.281503,3.214672,3.273712,...,3.241812,3.304688,3.270453,3.264001,3.275041,3.230244,3.206293,3.242960,3.292700,3.232404
2,3.269130,3.262126,3.262797,3.266916,3.266348,3.257010,3.275089,3.262973,3.291335,3.259665,...,3.262554,3.263657,3.268134,3.261278,3.260947,3.262332,3.242904,3.249078,3.265238,3.262665
3,3.278308,3.261333,3.263015,3.269048,3.268713,3.255820,3.251819,3.262969,3.226217,3.262553,...,3.263914,3.295029,3.263690,3.254054,3.261043,3.266115,3.233910,3.234644,3.241606,3.257638
4,3.270289,3.265751,3.266881,3.273094,3.271118,3.245915,3.288616,3.266195,3.298425,3.266049,...,3.261512,3.241697,3.259328,3.266174,3.264400,3.162986,3.254884,3.279272,3.275410,3.238708
5,3.257751,3.263378,3.263517,3.266500,3.265835,3.260997,3.255682,3.261547,3.252673,3.259639,...,3.262206,3.267556,3.263505,3.264437,3.262645,3.281044,3.255388,3.265963,3.253202,3.261755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,3.238802,3.296576,3.287313,3.282971,3.281284,3.297197,3.114133,3.266200,3.489591,3.294582,...,3.244757,3.216565,3.267049,3.305766,3.285991,3.406889,3.289724,3.399240,3.289298,3.305183
607,3.260418,3.265441,3.265114,3.265453,3.265263,3.267248,3.329225,3.264768,3.234182,3.266475,...,3.276077,3.273097,3.273139,3.266507,3.265475,3.349098,3.267380,3.247375,3.289425,3.253722
608,3.232333,3.287907,3.284631,3.275000,3.278255,3.305983,2.710363,3.275394,3.290014,3.277152,...,3.336994,3.277169,3.297220,3.304639,3.289044,4.178047,3.519986,3.288767,3.160835,3.318356
609,3.260100,3.262484,3.262822,3.266526,3.265954,3.258872,3.265436,3.262775,3.262526,3.261435,...,3.263970,3.263102,3.263472,3.263303,3.261575,3.280292,3.260212,3.263929,3.258838,3.260532
610,3.656218,3.256240,3.264216,3.261691,3.262752,3.265422,3.427140,3.255965,3.455047,3.299691,...,3.232712,3.730583,3.380556,3.112088,3.262177,3.262163,2.539848,2.293543,3.333058,3.265073

In [327]:
nmf_model.reconstruction_err_

280.4203420027937

In [328]:
error_squared = (ratings_pivot - R_hat)**2

error_squared

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.000838,1.896153e-04,1.587036e-04,1.264282e-04,1.458671e-04,0.000007,0.040032,3.674277e-04,2.271714e-03,1.294521e-04,...,4.211895e-04,1.793845e-03,0.000066,2.777300e-06,1.614463e-04,1.029780e-03,0.003141,0.000375,0.500273,8.958684e-04
2,0.000046,4.372105e-08,2.139852e-07,2.098939e-05,1.611009e-05,0.000028,0.000163,4.077074e-07,8.410174e-04,7.125825e-06,...,4.807862e-08,1.749166e-06,0.000034,1.116711e-06,1.925878e-06,5.073946e-12,0.000378,0.000176,0.000008,1.093133e-07
3,0.000255,1.003559e-06,4.631886e-07,4.506881e-05,4.068884e-05,0.000042,0.000111,4.022659e-07,1.304467e-03,4.773437e-08,...,2.495838e-06,1.068923e-03,0.000002,6.856102e-05,1.669528e-06,1.428777e-05,0.000808,0.000767,0.000430,2.205381e-05
4,0.000063,1.167119e-05,2.066754e-05,1.157554e-04,7.714283e-05,0.000270,0.000691,1.490550e-05,1.302487e-03,1.379356e-05,...,6.766056e-07,4.259176e-04,0.000009,1.474188e-05,4.263870e-06,9.870233e-03,0.000056,0.000287,0.000171,5.582067e-04
5,0.000021,1.088247e-06,1.397112e-06,1.734620e-05,1.225568e-05,0.000002,0.000044,6.196187e-07,9.333816e-05,7.265281e-06,...,1.667087e-08,2.726430e-05,0.000001,4.418940e-06,9.641292e-08,3.500412e-04,0.000048,0.000013,0.000083,3.359901e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.000554,1.172481e-03,6.239369e-04,4.258734e-04,3.590606e-04,0.001215,0.021964,1.494090e-05,5.164542e-02,1.039866e-03,...,3.089761e-04,2.094886e-03,0.000022,1.886269e-03,5.596087e-04,2.089584e-02,0.000750,0.018743,0.000727,1.836025e-03
607,0.000004,9.650192e-06,7.724837e-06,9.723678e-06,8.576921e-06,0.000024,0.004474,5.923053e-06,7.925451e-04,1.714047e-05,...,1.888463e-04,1.158191e-04,0.000117,1.740845e-05,9.861814e-06,7.527938e-03,0.000025,0.000224,0.000734,7.417182e-05
608,0.000900,6.539392e-04,4.971458e-04,1.604231e-04,2.534552e-04,0.001905,0.304673,1.705589e-04,7.661316e-04,2.195674e-04,...,5.574007e-03,2.200611e-04,0.001217,1.789701e-03,7.133829e-04,1.036538e-01,0.000399,0.000699,0.010302,3.138384e-03
609,0.000005,2.226776e-08,2.377960e-07,1.756628e-05,1.309961e-05,0.000012,0.000010,1.941163e-07,3.650717e-08,8.090465e-07,...,2.675317e-06,5.892889e-07,0.000001,9.369632e-07,5.764329e-07,3.224706e-04,0.000005,0.000003,0.000012,3.250819e-06
610,0.118186,3.714254e-05,3.539338e-06,4.142482e-07,1.738885e-07,0.000010,0.027161,4.057737e-05,2.020789e-03,1.395511e-03,...,8.775071e-04,7.258551e-02,0.014267,1.256368e-02,2.483810e-08,2.938812e-08,0.291436,0.629711,0.005002,7.498089e-06

In [329]:
error_squared.sum().sum()

78670.63674054295

In [330]:
np.sqrt(error_squared.sum().sum())

280.482863541684

### Export 3: Save a NFM-Model with pickle
The pickle module dumps an object into a binary strings

In [331]:
import pickle

with open('nmf_model1.pkl',mode='wb') as file:
    pickle.dump(nmf_model,file)

### Model deployment: Make recommendations for a new user
We want provide her/him with movie recommendations. So we ask him/her to rate some movie. For the new user $\hat{R}_{new-user}$ represents the user ratings if he/she would have watched the movies.

#### Step 1. Load a pickled Model

In [332]:
########## implementation #################

In [333]:
with open('nmf_model1.pkl','rb') as file:
    loaded_model = pickle.load(file)

In [334]:
loaded_model

NMF(max_iter=500, n_components=20)

In [335]:
new_user_query = {"Toy Story (1995)"   : 5,
                 "Heat (1995)"         : 2,
                 "Braveheart (1995)"   : 3.5}

In [336]:
new_user_query

{'Toy Story (1995)': 5, 'Heat (1995)': 2, 'Braveheart (1995)': 3.5}

In [337]:
movie_list = list(ratings_extended['title'].unique())

In [338]:
movie_list

['Toy Story (1995)',
 'Grumpier Old Men (1995)',
 'Heat (1995)',
 'Seven (a.k.a. Se7en) (1995)',
 'Usual Suspects, The (1995)',
 'From Dusk Till Dawn (1996)',
 'Bottle Rocket (1996)',
 'Braveheart (1995)',
 'Rob Roy (1995)',
 'Canadian Bacon (1995)',
 'Desperado (1995)',
 'Billy Madison (1995)',
 'Clerks (1994)',
 'Dumb & Dumber (Dumb and Dumber) (1994)',
 'Ed Wood (1994)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Pulp Fiction (1994)',
 'Stargate (1994)',
 'Tommy Boy (1995)',
 'Clear and Present Danger (1994)',
 'Forrest Gump (1994)',
 'Jungle Book, The (1994)',
 'Mask, The (1994)',
 'Blown Away (1994)',
 'Dazed and Confused (1993)',
 'Fugitive, The (1993)',
 'Jurassic Park (1993)',
 'Mrs. Doubtfire (1993)',
 "Schindler's List (1993)",
 'So I Married an Axe Murderer (1993)',
 'Three Musketeers, The (1993)',
 'Tombstone (1993)',
 'Dances with Wolves (1990)',
 'Batman (1989)',
 'Silence of the Lambs, The (1991)',
 'Pinocchio (1940)',
 'Fargo (1996)',
 'Mission: Impossible (1996)',
 'James and the Giant Peach (1996)',
 'Space Jam (1996)',
 'Rock, The (1996)',
 'Twister (1996)',
 'Independence Day (a.k.a. ID4) (1996)',
 "She's the One (1996)",
 'Wizard of Oz, The (1939)',
 'Citizen Kane (1941)',
 'Adventures of Robin Hood, The (1938)',
 'Ghost and Mrs. Muir, The (1947)',
 'Mr. Smith Goes to Washington (1939)',
 'Escape to Witch Mountain (1975)',
 'Winnie the Pooh and the Blustery Day (1968)',
 'Three Caballeros, The (1945)',
 'Sword in the Stone, The (1963)',
 'Dumbo (1941)',
 "Pete's Dragon (1977)",
 'Bedknobs and Broomsticks (1971)',
 'Alice in Wonderland (1951)',
 'That Thing You Do! (1996)',
 'Ghost and the Darkness, The (1996)',
 'Swingers (1996)',
 'Willy Wonka & the Chocolate Factory (1971)',
 "Monty Python's Life of Brian (1979)",
 'Reservoir Dogs (1992)',
 'Platoon (1986)',
 'Basic Instinct (1992)',
 'E.T. the Extra-Terrestrial (1982)',
 'Abyss, The (1989)',
 'Monty Python and the Holy Grail (1975)',
 'Star Wars: Episode V - The Empire Strikes Back (1980)',
 'Princess Bride, The (1987)',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)',
 'Clockwork Orange, A (1971)',
 'Apocalypse Now (1979)',
 'Star Wars: Episode VI - Return of the Jedi (1983)',
 'Goodfellas (1990)',
 'Alien (1979)',
 'Psycho (1960)',
 'Blues Brothers, The (1980)',
 'Full Metal Jacket (1987)',
 'Henry V (1989)',
 'Quiet Man, The (1952)',
 'Terminator, The (1984)',
 'Duck Soup (1933)',
 'Shining, The (1980)',
 'Groundhog Day (1993)',
 'Back to the Future (1985)',
 'Highlander (1986)',
 'Young Frankenstein (1974)',
 'Fantasia (1940)',
 'Indiana Jones and the Last Crusade (1989)',
 'Pink Floyd: The Wall (1982)',
 'Nosferatu (Nosferatu, eine Symphonie des Grauens) (1922)',
 'Batman Returns (1992)',
 'Sneakers (1992)',
 'Last of the Mohicans, The (1992)',
 "McHale's Navy (1997)",
 'Best Men (1997)',
 'Grosse Pointe Blank (1997)',
 'Austin Powers: International Man of Mystery (1997)',
 'Con Air (1997)',
 'Face/Off (1997)',
 'Men in Black (a.k.a. MIB) (1997)',
 'Conan the Barbarian (1982)',
 'L.A. Confidential (1997)',
 'Kiss the Girls (1997)',
 'Game, The (1997)',
 'I Know What You Did Last Summer (1997)',
 'Starship Troopers (1997)',
 'Big Lebowski, The (1998)',
 'Wedding Singer, The (1998)',
 'Welcome to Woop-Woop (1997)',
 'Newton Boys, The (1998)',
 'Wild Things (1998)',
 'Small Soldiers (1998)',
 'All Quiet on the Western Front (1930)',
 'Rocky (1976)',
 'Labyrinth (1986)',
 'Lethal Weapon (1987)',
 'Goonies, The (1985)',
 'Back to the Future Part III (1990)',
 'Bambi (1942)',
 'Saving Private Ryan (1998)',
 'Black Cauldron, The (1985)',
 'Flight of the Navigator (1986)',
 'Great Mouse Detective, The (1986)',
 'Honey, I Shrunk the Kids (1989)',
 'Negotiator, The (1998)',
 'Jungle Book, The (1967)',
 'Rescuers, The (1977)',
 'Return to Oz (1985)',
 'Rocketeer, The (1991)',
 'Sleeping Beauty (1959)',
 'Song of the South (1946)',
 'Tron (1982)',
 'Indiana Jones and the Temple of Doom (1984)',
 'Lord of the Rings, The (1978)',
 "Charlotte's Web (1973)",
 'Secret of NIMH, The (1982)',
 'American Tail, An (1986)',
 'Legend (1985)',
 'NeverEnding Story, The (1984)',
 'Beetlejuice (1988)',
 'Willow (1988)',
 'Toys (1992)',
 'Few Good Men, A (1992)',
 'Rush Hour (1998)',
 'Edward Scissorhands (1990)',
 'American History X (1998)',
 'I Still Know What You Did Last Summer (1998)',
 'Enemy of the State (1998)',
 'King Kong (1933)',
 'Very Bad Things (1998)',
 'Psycho (1998)',
 'Rushmore (1998)',
 'Romancing the Stone (1984)',
 'Young Sherlock Holmes (1985)',
 'Thin Red Line, The (1998)',
 'Howard the Duck (1986)',
 'Texas Chainsaw Massacre, The (1974)',
 'Crocodile Dundee (1986)',
 '¡Three Amigos! (1986)',
 '20 Dates (1998)',
 'Office Space (1999)',
 "Logan's Run (1976)",
 'Planet of the Apes (1968)',
 'Lock, Stock & Two Smoking Barrels (1998)',
 'Matrix, The (1999)',
 'Go (1999)',
 'SLC Punk! (1998)',
 'Dick Tracy (1990)',
 'Mummy, The (1999)',
 'Star Wars: Episode I - The Phantom Menace (1999)',
 'Superman (1978)',
 'Superman II (1980)',
 'Dracula (1931)',
 'Frankenstein (1931)',
 'Wolf Man, The (1941)',
 'Rocky Horror Picture Show, The (1975)',
 'Run Lola Run (Lola rennt) (1998)',
 'South Park: Bigger, Longer and Uncut (1999)',
 'Ghostbusters (a.k.a. Ghost Busters) (1984)',
 'Iron Giant, The (1999)',
 'Big (1988)',
 '13th Warrior, The (1999)',
 'American Beauty (1999)',
 'Excalibur (1981)',
 "Gulliver's Travels (1939)",
 'Total Recall (1990)',
 'Dirty Dozen, The (1967)',
 'Goldfinger (1964)',
 'From Russia with Love (1963)',
 'Dr. No (1962)',
 'Fight Club (1999)',
 'RoboCop (1987)',
 'Who Framed Roger Rabbit? (1988)',
 'Live and Let Die (1973)',
 'Thunderball (1965)',
 'Being John Malkovich (1999)',
 'Spaceballs (1987)',
 'Robin Hood (1973)',
 'Dogma (1999)',
 'Messenger: The Story of Joan of Arc, The (1999)',
 'Longest Day, The (1962)',
 'Green Mile, The (1999)',
 'Easy Rider (1969)',
 'Talented Mr. Ripley, The (1999)',
 'Encino Man (1992)',
 'Sister Act (1992)',
 "Wayne's World (1992)",
 'Scream 3 (2000)',
 'JFK (1991)',
 'Teenage Mutant Ninja Turtles II: The Secret of the Ooze (1991)',
 'Teenage Mutant Ninja Turtles III (1993)',
 'Red Dawn (1984)',
 'Good Morning, Vietnam (1987)',
 'Grumpy Old Men (1993)',
 'Ladyhawke (1985)',
 'Hook (1991)',
 'Predator (1987)',
 'Gladiator (2000)',
 'Road Trip (2000)',
 'Man with the Golden Gun, The (1974)',
 'Blazing Saddles (1974)',
 'Mad Max (1979)',
 'Road Warrior, The (Mad Max 2) (1981)',
 'Shaft (1971)',
 'Big Trouble in Little China (1986)',
 'Shaft (2000)',
 'X-Men (2000)',
 'What About Bob? (1991)',
 'Transformers: The Movie (1986)',
 'M*A*S*H (a.k.a. MASH) (1970)',
 'Shawshank Redemption, The (1994)',
 'Good Will Hunting (1997)',
 'Kill Bill: Vol. 1 (2003)',
 'Collateral (2004)',
 'Talladega Nights: The Ballad of Ricky Bobby (2006)',
 'Departed, The (2006)',
 'Dark Knight, The (2008)',
 'Step Brothers (2008)',
 'Inglourious Basterds (2009)',
 'Zombieland (2009)',
 'Shutter Island (2010)',
 'Exit Through the Gift Shop (2010)',
 'Inception (2010)',
 'Town, The (2010)',
 'Inside Job (2010)',
 'Louis C.K.: Hilarious (2010)',
 'Warrior (2011)',
 'Dark Knight Rises, The (2012)',
 'Girl with the Dragon Tattoo, The (2011)',
 'Django Unchained (2012)',
 'Wolf of Wall Street, The (2013)',
 'Interstellar (2014)',
 'Whiplash (2014)',
 'The Drop (2014)',
 'Ex Machina (2015)',
 'Mad Max: Fury Road (2015)',
 'The Jinx: The Life and Deaths of Robert Durst (2015)',
 'Dangerous Minds (1995)',
 'Courage Under Fire (1996)',
 'Operation Dumbo Drop (1995)',
 'Wallace & Gromit: The Best of Aardman Animation (1996)',
 'Escape from L.A. (1996)',
 'My Fair Lady (1964)',
 'Doors, The (1991)',
 'On Golden Pond (1981)',
 'Deer Hunter, The (1978)',
 'Patton (1970)',
 'Field of Dreams (1989)',
 'Star Trek: The Motion Picture (1979)',
 'Lady and the Tramp (1955)',
 'Thing, The (1982)',
 "You've Got Mail (1998)",
 'Piranha (1978)',
 'Fast Times at Ridgemont High (1982)',
 'Requiem for a Dream (2000)',
 'The Lair of the White Worm (1988)',
 'Snow Dogs (2002)',
 'Hangar 18 (1980)',
 'Galaxy of Terror (Quest) (1981)',
 'Looker (1981)',
 'Android (1982)',
 'Green Card (1990)',
 'Alien Contamination (1980)',
 'Master of the Flying Guillotine (Du bi quan wang da po xue di zi) (1975)',
 'Death Race 2000 (1975)',
 'Clonus Horror, The (1979)',
 'Troll 2 (1990)',
 '2012 (2009)',
 'Get Shorty (1995)',
 'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)',
 'To Die For (1995)',
 'Mighty Aphrodite (1995)',
 'Postman, The (Postino, Il) (1994)',
 'Nobody Loves Me (Keiner liebt mich) (1994)',
 'Flirting With Disaster (1996)',
 'NeverEnding Story III, The (1994)',
 'Crumb (1994)',
 'Jeffrey (1995)',
 'Living in Oblivion (1995)',
 'Safe (1995)',
 'Before Sunrise (1995)',
 'Circle of Friends (1995)',
 'Eat Drink Man Woman (Yin shi nan nu) (1994)',
 'Heavenly Creatures (1994)',
 'Like Water for Chocolate (Como agua para chocolate) (1992)',
 'Shallow Grave (1994)',
 "Muriel's Wedding (1994)",
 'Adventures of Priscilla, Queen of the Desert, The (1994)',
 'Bullets Over Broadway (1994)',
 'Corrina, Corrina (1994)',
 'Four Weddings and a Funeral (1994)',
 'Maverick (1994)',
 'Barcelona (1994)',
 'With Honors (1994)',
 'In the Name of the Father (1993)',
 'Manhattan Murder Mystery (1993)',
 'Piano, The (1993)',
 'Six Degrees of Separation (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Beauty and the Beast (1991)',
 'Wild Bunch, The (1969)',
 'Truth About Cats & Dogs, The (1996)',
 'Maya Lin: A Strong Clear Vision (1994)',
 'Lone Star (1996)',
 'Twelfth Night (1996)',
 'Philadelphia Story, The (1940)',
 "Singin' in the Rain (1952)",
 "Breakfast at Tiffany's (1961)",
 'Rear Window (1954)',
 'North by Northwest (1959)',
 'Some Like It Hot (1959)',
 'Casablanca (1942)',
 'Gone with the Wind (1939)',
 'Notorious (1946)',
 'Love in the Afternoon (1957)',
 'Beautiful Thing (1996)',
 'Everyone Says I Love You (1996)',
 'Sleeper (1973)',
 'Fish Called Wanda, A (1988)',
 'Bonnie and Clyde (1967)',
 'Dial M for Murder (1954)',
 'Crying Game, The (1992)',
 'Rebel Without a Cause (1955)',
 'Grifters, The (1990)',
 'English Patient, The (1996)',
 'Strictly Ballroom (1992)',
 'Brazil (1985)',
 '12 Angry Men (1957)',
 'Wings of Desire (Himmel über Berlin, Der) (1987)',
 'Amadeus (1984)',
 'Bridge on the River Kwai, The (1957)',
 'Stand by Me (1986)',
 'Unforgiven (1992)',
 'Night on Earth (1991)',
 'High Noon (1952)',
 'This Is Spinal Tap (1984)',
 'Butch Cassidy and the Sundance Kid (1969)',
 'Mars Attacks! (1996)',
 'Waiting for Guffman (1996)',
 'Donnie Brasco (1997)',
 'Conspiracy Theory (1997)',
 'Full Monty, The (1997)',
 'Sweet Hereafter, The (1997)',
 'Afterglow (1997)',
 'My Life in Pink (Ma vie en rose) (1997)',
 'Spanish Prisoner, The (1997)',
 'Character (Karakter) (1997)',
 'Bulworth (1998)',
 'Opposite of Sex, The (1998)',
 'Perfect Murder, A (1998)',
 "Can't Hardly Wait (1998)",
 'Mulan (1998)',
 'Smoke Signals (1998)',
 "Buffalo '66 (a.k.a. Buffalo 66) (1998)",
 "There's Something About Mary (1998)",
 'West Side Story (1961)',
 'Metropolitan (1990)',
 'Breakfast Club, The (1985)',
 'Seven Samurai (Shichinin no samurai) (1954)',
 'Blue Velvet (1986)',
 'Jerk, The (1979)',
 'Pretty in Pink (1986)',
 'Gods Must Be Crazy, The (1980)',
 'Strangers on a Train (1951)',
 'Shadow of a Doubt (1943)',
 'Saboteur (1942)',
 'Pecker (1998)',
 'Life Is Beautiful (La Vita è bella) (1997)',
 'Elizabeth (1998)',
 'Nights of Cabiria (Notti di Cabiria, Le) (1957)',
 'Waking Ned Devine (a.k.a. Waking Ned) (1998)',
 'Little Voice (1998)',
 'Name of the Rose, The (Name der Rose, Der) (1986)',
 "Cookie's Fortune (1999)",
 'Election (1999)',
 'Austin Powers: The Spy Who Shagged Me (1999)',
 'Eyes Wide Shut (1999)',
 'Sixth Sense, The (1999)',
 'Thomas Crown Affair, The (1999)',
 'Bowfinger (1999)',
 'Airplane! (1980)',
 'Black Cat, White Cat (Crna macka, beli macor) (1998)',
 'Pajama Game, The (1957)',
 'High Plains Drifter (1973)',
 'Hairspray (1988)',
 'Crimes and Misdemeanors (1989)',
 'Dead Again (1991)',
 'Commitments, The (1991)',
 'Mansfield Park (1999)',
 'All About My Mother (Todo sobre mi madre) (1999)',
 'Magnolia (1999)',
 'Galaxy Quest (1999)',
 'Boys from Brazil, The (1978)',
 'League of Their Own, A (1992)',
 'Wonder Boys (2000)',
 'Defending Your Life (1991)',
 'Searchers, The (1956)',
 'Erin Brockovich (2000)',
 'High Fidelity (2000)',
 'Outlaw Josey Wales, The (1976)',
 'East is East (1999)',
 'Mr. Mom (1983)',
 'Blow-Up (Blowup) (1966)',
 "I'm the One That I Want (2000)",
 'Almost Famous (2000)',
 'Best in Show (2000)',
 'Billy Elliot (2000)',
 'Crouching Tiger, Hidden Dragon (Wo hu cang long) (2000)',
 'Planes, Trains & Automobiles (1987)',
 'Chocolat (2000)',
 'Gift, The (2000)',
 'Before Night Falls (2000)',
 'O Brother, Where Art Thou? (2000)',
 'State and Main (2000)',
 'Thirteen Days (2000)',
 'Traffic (2000)',
 'Legend of Rita, The (Stille nach dem Schuß, Die) (1999)',
 'Innerspace (1987)',
 'In the Mood For Love (Fa yeung nin wa) (2000)',
 'Series 7: The Contenders (2001)',
 'Memento (2000)',
 'Blow (2001)',
 "Bridget Jones's Diary (2001)",
 'Circle, The (Dayereh) (2000)',
 'Visit, The (2000)',
 'Under the Sand (2000)',
 'Moulin Rouge (2001)',
 'Divided We Fall (Musíme si pomáhat) (2000)',
 'Closet, The (Placard, Le) (2001)',
 'Ghost World (2001)',
 'Together (Tillsammans) (2000)',
 'L.I.E. (2001)',
 "Man Who Wasn't There, The (2001)",
 "Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)",
 "Devil's Backbone, The (Espinazo del diablo, El) (2001)",
 "No Man's Land (2001)",
 'Babe (1995)',
 'Dead Man Walking (1995)',
 'Clueless (1995)',
 'Apollo 13 (1995)',
 'Batman Forever (1995)',
 'Interview with the Vampire: The Vampire Chronicles (1994)',
 'Little Women (1994)',
 'Legends of the Fall (1994)',
 'Once Were Warriors (1994)',
 'Quiz Show (1994)',
 'Ace Ventura: Pet Detective (1994)',
 'Lion King, The (1994)',
 'True Lies (1994)',
 'Addams Family Values (1993)',
 'In the Line of Fire (1993)',
 'Remains of the Day, The (1993)',
 'Secret Garden, The (1993)',
 'Shadowlands (1993)',
 'Terminator 2: Judgment Day (1991)',
 'Snow White and the Seven Dwarfs (1937)',
 'Pretty Woman (1990)',
 'Jumanji (1995)',
 'Waiting to Exhale (1995)',
 'Father of the Bride Part II (1995)',
 'Sabrina (1995)',
 'Tom and Huck (1995)',
 'GoldenEye (1995)',
 'American President, The (1995)',
 'Balto (1995)',
 'Cutthroat Island (1995)',
 'Casino (1995)',
 'Sense and Sensibility (1995)',
 'Ace Ventura: When Nature Calls (1995)',
 'Copycat (1995)',
 'Powder (1995)',
 'Leaving Las Vegas (1995)',
 'Othello (1995)',
 'Now and Then (1995)',
 'Richard III (1995)',
 'Restoration (1995)',
 'How to Make an American Quilt (1995)',
 'Big Green, The (1995)',
 'Indian in the Cupboard, The (1995)',
 'Eye for an Eye (1996)',
 "Mr. Holland's Opus (1995)",
 'Bio-Dome (1996)',
 'Lawnmower Man 2: Beyond Cyberspace (1996)',
 'Screamers (1995)',
 'Juror, The (1996)',
 'White Squall (1996)',
 'Dunston Checks In (1996)',
 'Black Sheep (1996)',
 'Nick of Time (1995)',
 'Mary Reilly (1996)',
 'Vampire in Brooklyn (1995)',
 'Broken Arrow (1996)',
 'City Hall (1996)',
 'Mr. Wrong (1996)',
 'Happy Gilmore (1996)',
 'Bridges of Madison County, The (1995)',
 'Rumble in the Bronx (Hont faan kui) (1995)',
 'Before and After (1996)',
 'Down Periscope (1996)',
 'Up Close and Personal (1996)',
 'Birdcage, The (1996)',
 'Bad Boys (1995)',
 'Amazing Panda Adventure, The (1995)',
 'Casper (1995)',
 'Clockers (1995)',
 'Congo (1995)',
 'Crimson Tide (1995)',
 'Die Hard: With a Vengeance (1995)',
 'First Knight (1995)',
 'Hackers (1995)',
 'Jury Duty (1995)',
 'Lord of Illusions (1995)',
 'Mad Love (1995)',
 'Mallrats (1995)',
 'Mighty Morphin Power Rangers: The Movie (1995)',
 'Net, The (1995)',
 'Nine Months (1995)',
 'Reckless (1995)',
 'Scarlet Letter, The (1995)',
 'Something to Talk About (1995)',
 'Species (1995)',
 'Three Wishes (1995)',
 'Under Siege 2: Dark Territory (1995)',
 'Unstrung Heroes (1995)',
 'Walk in the Clouds, A (1995)',
 'Waterworld (1995)',
 "White Man's Burden (1995)",
 'Wild Bill (1995)',
 'Bushwhacked (1995)',
 'Babysitter, The (1995)',
 'Boys on the Side (1995)',
 'Cure, The (1995)',
 'Don Juan DeMarco (1995)',
 'Disclosure (1994)',
 'Dolores Claiborne (1995)',
 'Exit to Eden (1994)',
 'French Kiss (1995)',
 'Forget Paris (1995)',
 'Goofy Movie, A (1995)',
 'Hideaway (1995)',
 'Gordy (1995)',
 'Houseguest (1994)',
 'Heavyweights (Heavy Weights) (1995)',
 'Hunted, The (1995)',
 'I.Q. (1994)',
 'Jefferson in Paris (1995)',
 'Junior (1994)',
 'Just Cause (1995)',
 "Kid in King Arthur's Court, A (1995)",
 'Little Princess, A (1995)',
 'Major Payne (1995)',
 'Love Affair (1994)',
 'Losing Isaiah (1995)',
 "Mary Shelley's Frankenstein (Frankenstein) (1994)",
 'Man of the House (1995)',
 'Milk Money (1994)',
 'Miracle on 34th Street (1994)',
 'My Family (1995)',
 "Nobody's Fool (1994)",
 'Nell (1994)',
 'Natural Born Killers (1994)',
 'Only You (1994)',
 'Poison Ivy II (1996)',
 'Outbreak (1995)',
 'Léon: The Professional (a.k.a. The Professional) (Léon) (1994)',
 'Queen Margot (Reine Margot, La) (1994)',
 'Quick and the Dead, The (1995)',
 'Roommates (1995)',
 'Rent-a-Kid (1995)',
 'Stuart Saves His Family (1995)',
 'Swan Princess, The (1994)',
 'Secret of Roan Inish, The (1994)',
 'Specialist, The (1994)',
 'Santa Clause, The (1994)',
 'Tank Girl (1995)',
 'Star Trek: Generations (1994)',
 'Tales from the Hood (1995)',
 'Village of the Damned (1995)',
 'Walking Dead, The (1995)',
 "What's Eating Gilbert Grape (1993)",
 'While You Were Sleeping (1995)',
 'War, The (1994)',
 'Baby-Sitters Club, The (1995)',
 'Bitter Moon (1992)',
 'Client, The (1994)',
 'Crooklyn (1994)',
 'Crow, The (1994)',
 'Cobb (1994)',
 'Flintstones, The (1994)',
 'Higher Learning (1995)',
 'I Like It Like That (1994)',
 'I Love Trouble (1994)',
 'It Could Happen to You (1994)',
 "Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A) (1994)",
 'Naked Gun 33 1/3: The Final Insult (1994)',
 'Paper, The (1994)',
 'Richie Rich (1994)',
 'Speed (1994)',
 'Speechless (1994)',
 'When a Man Loves a Woman (1994)',
 'Wolf (1994)',
 'Wyatt Earp (1994)',
 'Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension) (1994)',
 'Age of Innocence, The (1993)',
 'Another Stakeout (1993)',
 'Bad Girls (1994)',
 'Beverly Hillbillies, The (1993)',
 'Body Snatchers (1993)',
 "City Slickers II: The Legend of Curly's Gold (1994)",
 'Cliffhanger (1993)',
 'Coneheads (1993)',
 'Cops and Robbersons (1994)',
 'Dave (1993)',
 'Fatal Instinct (1993)',
 'Firm, The (1993)',
 'Free Willy (1993)',
 'Geronimo: An American Legend (1993)',
 'Getting Even with Dad (1994)',
 'Hot Shots! Part Deux (1993)',
 'Englishman Who Went Up a Hill But Came Down a Mountain, The (1995)',
 'House of the Spirits, The (1993)',
 "I'll Do Anything (1994)",
 "What's Love Got to Do with It? (1993)",
 'Last Action Hero (1993)',
 'Made in America (1993)',
 'Malice (1993)',
 'Man Without a Face, The (1993)',
 'Menace II Society (1993)',
 'Executive Decision (1996)',
 'Much Ado About Nothing (1993)',
 'Next Karate Kid, The (1994)',
 'North (1994)',
 'Philadelphia (1993)',
 'Poetic Justice (1993)',
 'Renaissance Man (1994)',
 'Robin Hood: Men in Tights (1993)',
 'Rudy (1993)',
 'Serial Mom (1994)',
 'Simple Twist of Fate, A (1994)',
 'Sirens (1994)',
 'Sliver (1993)',
 'Son in Law (1993)',
 'Super Mario Bros. (1993)',
 'Terminal Velocity (1994)',
 'Little Big League (1994)',
 'Little Rascals, The (1994)',
 'Ghost (1990)',
 'Candyman: Farewell to the Flesh (1995)',
 'Homeward Bound II: Lost in San Francisco (1996)',
 'Aristocats, The (1970)',
 'Primal Fear (1996)',
 'All Dogs Go to Heaven 2 (1996)',
 'Sgt. Bilko (1996)',
 'Diabolique (1996)',
 'Fear (1996)',
 'Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite) (1996)',
 'Substitute, The (1996)',
 'Feeling Minnesota (1996)',
 'Angus (1995)',
 'Quest, The (1996)',
 'Oliver & Company (1988)',
 'Celtic Pride (1996)',

In [339]:
new_user_dataframe =  pd.DataFrame(data    = new_user_query,
                                   columns = movie_list,
                                   index   = ['new_user']
                                  )

In [340]:
new_user_dataframe#.dropna()

,Toy Story (1995),Grumpier Old Men (1995),Heat (1995),Seven (a.k.a. Se7en) (1995),"Usual Suspects, The (1995)",From Dusk Till Dawn (1996),Bottle Rocket (1996),Braveheart (1995),Rob Roy (1995),Canadian Bacon (1995),...,Return of the One-Armed Swordsman (1969),Hitchcock/Truffaut (2015),He Never Died (2015),Southbound (2016),Gen-X Cops (1999),Bloodmoon (1997),Sympathy for the Underdog (1971),Hazard (2005),Blair Witch (2016),31 (2016)
new_user,5,NaN,2,NaN,NaN,NaN,NaN,3.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [392]:
ratings_pivot.to_csv("ratings_pivot.csv")

In [390]:
ratings_pivot.mean()

title
'71 (2014)                                   3.263544
'Hellboy': The Seeds of Creation (2004)      3.263544
'Round Midnight (1986)                       3.263114
'Salem's Lot (2004)                          3.265183
'Til There Was You (1997)                    3.264753
                                               ...
eXistenZ (1999)                              3.284021
xXx (2002)                                   3.242997
xXx: State of the Union (2005)               3.251988
¡Three Amigos! (1986)                        3.256891
À nous la liberté (Freedom for Us) (1931)    3.258626
Length: 9719, dtype: float64

3. *Fill the missing value*<br>

In [341]:
# using the same imputation as training data

new_user_dataframe_imputed = new_user_dataframe.fillna(ratings_pivot.mean())
new_user_dataframe_imputed

,Toy Story (1995),Grumpier Old Men (1995),Heat (1995),Seven (a.k.a. Se7en) (1995),"Usual Suspects, The (1995)",From Dusk Till Dawn (1996),Bottle Rocket (1996),Braveheart (1995),Rob Roy (1995),Canadian Bacon (1995),...,Return of the One-Armed Swordsman (1969),Hitchcock/Truffaut (2015),He Never Died (2015),Southbound (2016),Gen-X Cops (1999),Bloodmoon (1997),Sympathy for the Underdog (1971),Hazard (2005),Blair Witch (2016),31 (2016)
new_user,5,3.262103,2,3.499623,3.588537,3.284583,3.281952,3.5,3.282756,3.255145,...,3.261905,3.262724,3.262724,3.262724,3.262724,3.261085,3.264364,3.261905,3.262724,3.262724

#### Step 3. Create user-feature matrix $P$ for new user

1. *Get the user-feature matrix/dataframe $P$ by using the model method transform on the full imputed user/movie dataframe/matrix*

In [342]:
P_new_user_matrix = nmf_model.transform(new_user_dataframe_imputed)

/home/florianriemann/anaconda3/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

In [343]:
P_new_user_matrix

array([[3.4716681 , 0.51405783, 0.06683634, 0.15582413, 0.0888813 ,
        0.18289124, 0.11052328, 0.22402921, 0.22478723, 0.17440639,
        0.1173122 , 0.07760469, 0.11405457, 0.23693922, 0.16978672,
        0.16548433, 0.29209746, 0.15348713, 0.10084882, 0.14003144]])

In [344]:
P_new_user = pd.DataFrame(data=P_new_user_matrix,
                         index = ['new_user'])

In [345]:
P_new_user

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
new_user,3.471668,0.514058,0.066836,0.155824,0.088881,0.182891,0.110523,0.224029,0.224787,0.174406,0.117312,0.077605,0.114055,0.236939,0.169787,0.165484,0.292097,0.153487,0.100849,0.140031

#### Step 3. Reconstruct the user-movie(item) matrix/dataframe for the new user
$\hat{R}_{new-user} = P_{new-user} \cdot Q \sim R_{new-user}$

In [395]:
R_hat_new_user_matrix = np.dot(P_new_user_matrix, Q_matrix)
R_hat_new_user_matrix

array([[3.26736427, 3.26703408, 3.26768539, ..., 3.26965063, 3.25858614,
        3.26365697]])

In [422]:
prediction = pd.DataFrame(R_hat_new_user_matrix, columns=new_user_dataframe_imputed.columns)
prediction = prediction.T
prediction.rename(columns={0:"movies"}, inplace=True)
prediction = prediction.sort_values(by='movies', ascending=False)
prediction = list(prediction.head(10).index)
prediction

['Secret of My Succe$s, The (a.k.a. The Secret of My Success) (1987)',
 'Dylan Moran: Monster (2004)',
 'It Comes at Night (2017)',
 'A Story of Children and Film (2013)',
 'Suspiria (1977)',
 'Earth vs. the Flying Saucers (1956)',
 'Ashby (2015)',
 'Bronx Tale, A (1993)',
 'Heavyweights (Heavy Weights) (1995)',
 'Loser (1991)']

### Export 4: movie_list

In [385]:
movie_list_df = pd.DataFrame(movie_list, columns=['movies'])

In [386]:
movie_list_df.to_csv('movie_list_df.csv')

In [387]:
movie_list_df = pd.read_csv('movie_list_df.csv')

In [389]:
movie_list = list(movie_list_df['movies'])

['Toy Story (1995)',
 'Grumpier Old Men (1995)',
 'Heat (1995)',
 'Seven (a.k.a. Se7en) (1995)',
 'Usual Suspects, The (1995)',
 'From Dusk Till Dawn (1996)',
 'Bottle Rocket (1996)',
 'Braveheart (1995)',
 'Rob Roy (1995)',
 'Canadian Bacon (1995)',
 'Desperado (1995)',
 'Billy Madison (1995)',
 'Clerks (1994)',
 'Dumb & Dumber (Dumb and Dumber) (1994)',
 'Ed Wood (1994)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Pulp Fiction (1994)',
 'Stargate (1994)',
 'Tommy Boy (1995)',
 'Clear and Present Danger (1994)',
 'Forrest Gump (1994)',
 'Jungle Book, The (1994)',
 'Mask, The (1994)',
 'Blown Away (1994)',
 'Dazed and Confused (1993)',
 'Fugitive, The (1993)',
 'Jurassic Park (1993)',
 'Mrs. Doubtfire (1993)',
 "Schindler's List (1993)",
 'So I Married an Axe Murderer (1993)',
 'Three Musketeers, The (1993)',
 'Tombstone (1993)',
 'Dances with Wolves (1990)',
 'Batman (1989)',
 'Silence of the Lambs, The (1991)',
 'Pinocchio (1940)',
 'Fargo (1996)',
 'Mission: Impossible (1996)',
 'James and the Giant Peach (1996)',
 'Space Jam (1996)',
 'Rock, The (1996)',
 'Twister (1996)',
 'Independence Day (a.k.a. ID4) (1996)',
 "She's the One (1996)",
 'Wizard of Oz, The (1939)',
 'Citizen Kane (1941)',
 'Adventures of Robin Hood, The (1938)',
 'Ghost and Mrs. Muir, The (1947)',
 'Mr. Smith Goes to Washington (1939)',
 'Escape to Witch Mountain (1975)',
 'Winnie the Pooh and the Blustery Day (1968)',
 'Three Caballeros, The (1945)',
 'Sword in the Stone, The (1963)',
 'Dumbo (1941)',
 "Pete's Dragon (1977)",
 'Bedknobs and Broomsticks (1971)',
 'Alice in Wonderland (1951)',
 'That Thing You Do! (1996)',
 'Ghost and the Darkness, The (1996)',
 'Swingers (1996)',
 'Willy Wonka & the Chocolate Factory (1971)',
 "Monty Python's Life of Brian (1979)",
 'Reservoir Dogs (1992)',
 'Platoon (1986)',
 'Basic Instinct (1992)',
 'E.T. the Extra-Terrestrial (1982)',
 'Abyss, The (1989)',
 'Monty Python and the Holy Grail (1975)',
 'Star Wars: Episode V - The Empire Strikes Back (1980)',
 'Princess Bride, The (1987)',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)',
 'Clockwork Orange, A (1971)',
 'Apocalypse Now (1979)',
 'Star Wars: Episode VI - Return of the Jedi (1983)',
 'Goodfellas (1990)',
 'Alien (1979)',
 'Psycho (1960)',
 'Blues Brothers, The (1980)',
 'Full Metal Jacket (1987)',
 'Henry V (1989)',
 'Quiet Man, The (1952)',
 'Terminator, The (1984)',
 'Duck Soup (1933)',
 'Shining, The (1980)',
 'Groundhog Day (1993)',
 'Back to the Future (1985)',
 'Highlander (1986)',
 'Young Frankenstein (1974)',
 'Fantasia (1940)',
 'Indiana Jones and the Last Crusade (1989)',
 'Pink Floyd: The Wall (1982)',
 'Nosferatu (Nosferatu, eine Symphonie des Grauens) (1922)',
 'Batman Returns (1992)',
 'Sneakers (1992)',
 'Last of the Mohicans, The (1992)',
 "McHale's Navy (1997)",
 'Best Men (1997)',
 'Grosse Pointe Blank (1997)',
 'Austin Powers: International Man of Mystery (1997)',
 'Con Air (1997)',
 'Face/Off (1997)',
 'Men in Black (a.k.a. MIB) (1997)',
 'Conan the Barbarian (1982)',
 'L.A. Confidential (1997)',
 'Kiss the Girls (1997)',
 'Game, The (1997)',
 'I Know What You Did Last Summer (1997)',
 'Starship Troopers (1997)',
 'Big Lebowski, The (1998)',
 'Wedding Singer, The (1998)',
 'Welcome to Woop-Woop (1997)',
 'Newton Boys, The (1998)',
 'Wild Things (1998)',
 'Small Soldiers (1998)',
 'All Quiet on the Western Front (1930)',
 'Rocky (1976)',
 'Labyrinth (1986)',
 'Lethal Weapon (1987)',
 'Goonies, The (1985)',
 'Back to the Future Part III (1990)',
 'Bambi (1942)',
 'Saving Private Ryan (1998)',
 'Black Cauldron, The (1985)',
 'Flight of the Navigator (1986)',
 'Great Mouse Detective, The (1986)',
 'Honey, I Shrunk the Kids (1989)',
 'Negotiator, The (1998)',
 'Jungle Book, The (1967)',
 'Rescuers, The (1977)',
 'Return to Oz (1985)',
 'Rocketeer, The (1991)',
 'Sleeping Beauty (1959)',
 'Song of the South (1946)',
 'Tron (1982)',
 'Indiana Jones and the Temple of Doom (1984)',
 'Lord of the Rings, The (1978)',
 "Charlotte's Web (1973)",
 'Secret of NIMH, The (1982)',
 'American Tail, An (1986)',
 'Legend (1985)',
 'NeverEnding Story, The (1984)',
 'Beetlejuice (1988)',
 'Willow (1988)',
 'Toys (1992)',
 'Few Good Men, A (1992)',
 'Rush Hour (1998)',
 'Edward Scissorhands (1990)',
 'American History X (1998)',
 'I Still Know What You Did Last Summer (1998)',
 'Enemy of the State (1998)',
 'King Kong (1933)',
 'Very Bad Things (1998)',
 'Psycho (1998)',
 'Rushmore (1998)',
 'Romancing the Stone (1984)',
 'Young Sherlock Holmes (1985)',
 'Thin Red Line, The (1998)',
 'Howard the Duck (1986)',
 'Texas Chainsaw Massacre, The (1974)',
 'Crocodile Dundee (1986)',
 '¡Three Amigos! (1986)',
 '20 Dates (1998)',
 'Office Space (1999)',
 "Logan's Run (1976)",
 'Planet of the Apes (1968)',
 'Lock, Stock & Two Smoking Barrels (1998)',
 'Matrix, The (1999)',
 'Go (1999)',
 'SLC Punk! (1998)',
 'Dick Tracy (1990)',
 'Mummy, The (1999)',
 'Star Wars: Episode I - The Phantom Menace (1999)',
 'Superman (1978)',
 'Superman II (1980)',
 'Dracula (1931)',
 'Frankenstein (1931)',
 'Wolf Man, The (1941)',
 'Rocky Horror Picture Show, The (1975)',
 'Run Lola Run (Lola rennt) (1998)',
 'South Park: Bigger, Longer and Uncut (1999)',
 'Ghostbusters (a.k.a. Ghost Busters) (1984)',
 'Iron Giant, The (1999)',
 'Big (1988)',
 '13th Warrior, The (1999)',
 'American Beauty (1999)',
 'Excalibur (1981)',
 "Gulliver's Travels (1939)",
 'Total Recall (1990)',
 'Dirty Dozen, The (1967)',
 'Goldfinger (1964)',
 'From Russia with Love (1963)',
 'Dr. No (1962)',
 'Fight Club (1999)',
 'RoboCop (1987)',
 'Who Framed Roger Rabbit? (1988)',
 'Live and Let Die (1973)',
 'Thunderball (1965)',
 'Being John Malkovich (1999)',
 'Spaceballs (1987)',
 'Robin Hood (1973)',
 'Dogma (1999)',
 'Messenger: The Story of Joan of Arc, The (1999)',
 'Longest Day, The (1962)',
 'Green Mile, The (1999)',
 'Easy Rider (1969)',
 'Talented Mr. Ripley, The (1999)',
 'Encino Man (1992)',
 'Sister Act (1992)',
 "Wayne's World (1992)",
 'Scream 3 (2000)',
 'JFK (1991)',
 'Teenage Mutant Ninja Turtles II: The Secret of the Ooze (1991)',
 'Teenage Mutant Ninja Turtles III (1993)',
 'Red Dawn (1984)',
 'Good Morning, Vietnam (1987)',
 'Grumpy Old Men (1993)',
 'Ladyhawke (1985)',
 'Hook (1991)',
 'Predator (1987)',
 'Gladiator (2000)',
 'Road Trip (2000)',
 'Man with the Golden Gun, The (1974)',
 'Blazing Saddles (1974)',
 'Mad Max (1979)',
 'Road Warrior, The (Mad Max 2) (1981)',
 'Shaft (1971)',
 'Big Trouble in Little China (1986)',
 'Shaft (2000)',
 'X-Men (2000)',
 'What About Bob? (1991)',
 'Transformers: The Movie (1986)',
 'M*A*S*H (a.k.a. MASH) (1970)',
 'Shawshank Redemption, The (1994)',
 'Good Will Hunting (1997)',
 'Kill Bill: Vol. 1 (2003)',
 'Collateral (2004)',
 'Talladega Nights: The Ballad of Ricky Bobby (2006)',
 'Departed, The (2006)',
 'Dark Knight, The (2008)',
 'Step Brothers (2008)',
 'Inglourious Basterds (2009)',
 'Zombieland (2009)',
 'Shutter Island (2010)',
 'Exit Through the Gift Shop (2010)',
 'Inception (2010)',
 'Town, The (2010)',
 'Inside Job (2010)',
 'Louis C.K.: Hilarious (2010)',
 'Warrior (2011)',
 'Dark Knight Rises, The (2012)',
 'Girl with the Dragon Tattoo, The (2011)',
 'Django Unchained (2012)',
 'Wolf of Wall Street, The (2013)',
 'Interstellar (2014)',
 'Whiplash (2014)',
 'The Drop (2014)',
 'Ex Machina (2015)',
 'Mad Max: Fury Road (2015)',
 'The Jinx: The Life and Deaths of Robert Durst (2015)',
 'Dangerous Minds (1995)',
 'Courage Under Fire (1996)',
 'Operation Dumbo Drop (1995)',
 'Wallace & Gromit: The Best of Aardman Animation (1996)',
 'Escape from L.A. (1996)',
 'My Fair Lady (1964)',
 'Doors, The (1991)',
 'On Golden Pond (1981)',
 'Deer Hunter, The (1978)',
 'Patton (1970)',
 'Field of Dreams (1989)',
 'Star Trek: The Motion Picture (1979)',
 'Lady and the Tramp (1955)',
 'Thing, The (1982)',
 "You've Got Mail (1998)",
 'Piranha (1978)',
 'Fast Times at Ridgemont High (1982)',
 'Requiem for a Dream (2000)',
 'The Lair of the White Worm (1988)',
 'Snow Dogs (2002)',
 'Hangar 18 (1980)',
 'Galaxy of Terror (Quest) (1981)',
 'Looker (1981)',
 'Android (1982)',
 'Green Card (1990)',
 'Alien Contamination (1980)',
 'Master of the Flying Guillotine (Du bi quan wang da po xue di zi) (1975)',
 'Death Race 2000 (1975)',
 'Clonus Horror, The (1979)',
 'Troll 2 (1990)',
 '2012 (2009)',
 'Get Shorty (1995)',
 'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)',
 'To Die For (1995)',
 'Mighty Aphrodite (1995)',
 'Postman, The (Postino, Il) (1994)',
 'Nobody Loves Me (Keiner liebt mich) (1994)',
 'Flirting With Disaster (1996)',
 'NeverEnding Story III, The (1994)',
 'Crumb (1994)',
 'Jeffrey (1995)',
 'Living in Oblivion (1995)',
 'Safe (1995)',
 'Before Sunrise (1995)',
 'Circle of Friends (1995)',
 'Eat Drink Man Woman (Yin shi nan nu) (1994)',
 'Heavenly Creatures (1994)',
 'Like Water for Chocolate (Como agua para chocolate) (1992)',
 'Shallow Grave (1994)',
 "Muriel's Wedding (1994)",
 'Adventures of Priscilla, Queen of the Desert, The (1994)',
 'Bullets Over Broadway (1994)',
 'Corrina, Corrina (1994)',
 'Four Weddings and a Funeral (1994)',
 'Maverick (1994)',
 'Barcelona (1994)',
 'With Honors (1994)',
 'In the Name of the Father (1993)',
 'Manhattan Murder Mystery (1993)',
 'Piano, The (1993)',
 'Six Degrees of Separation (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Beauty and the Beast (1991)',
 'Wild Bunch, The (1969)',
 'Truth About Cats & Dogs, The (1996)',
 'Maya Lin: A Strong Clear Vision (1994)',
 'Lone Star (1996)',
 'Twelfth Night (1996)',
 'Philadelphia Story, The (1940)',
 "Singin' in the Rain (1952)",
 "Breakfast at Tiffany's (1961)",
 'Rear Window (1954)',
 'North by Northwest (1959)',
 'Some Like It Hot (1959)',
 'Casablanca (1942)',
 'Gone with the Wind (1939)',
 'Notorious (1946)',
 'Love in the Afternoon (1957)',
 'Beautiful Thing (1996)',
 'Everyone Says I Love You (1996)',
 'Sleeper (1973)',
 'Fish Called Wanda, A (1988)',
 'Bonnie and Clyde (1967)',
 'Dial M for Murder (1954)',
 'Crying Game, The (1992)',
 'Rebel Without a Cause (1955)',
 'Grifters, The (1990)',
 'English Patient, The (1996)',
 'Strictly Ballroom (1992)',
 'Brazil (1985)',
 '12 Angry Men (1957)',
 'Wings of Desire (Himmel über Berlin, Der) (1987)',
 'Amadeus (1984)',
 'Bridge on the River Kwai, The (1957)',
 'Stand by Me (1986)',
 'Unforgiven (1992)',
 'Night on Earth (1991)',
 'High Noon (1952)',
 'This Is Spinal Tap (1984)',
 'Butch Cassidy and the Sundance Kid (1969)',
 'Mars Attacks! (1996)',
 'Waiting for Guffman (1996)',
 'Donnie Brasco (1997)',
 'Conspiracy Theory (1997)',
 'Full Monty, The (1997)',
 'Sweet Hereafter, The (1997)',
 'Afterglow (1997)',
 'My Life in Pink (Ma vie en rose) (1997)',
 'Spanish Prisoner, The (1997)',
 'Character (Karakter) (1997)',
 'Bulworth (1998)',
 'Opposite of Sex, The (1998)',
 'Perfect Murder, A (1998)',
 "Can't Hardly Wait (1998)",
 'Mulan (1998)',
 'Smoke Signals (1998)',
 "Buffalo '66 (a.k.a. Buffalo 66) (1998)",
 "There's Something About Mary (1998)",
 'West Side Story (1961)',
 'Metropolitan (1990)',
 'Breakfast Club, The (1985)',
 'Seven Samurai (Shichinin no samurai) (1954)',
 'Blue Velvet (1986)',
 'Jerk, The (1979)',
 'Pretty in Pink (1986)',
 'Gods Must Be Crazy, The (1980)',
 'Strangers on a Train (1951)',
 'Shadow of a Doubt (1943)',
 'Saboteur (1942)',
 'Pecker (1998)',
 'Life Is Beautiful (La Vita è bella) (1997)',
 'Elizabeth (1998)',
 'Nights of Cabiria (Notti di Cabiria, Le) (1957)',
 'Waking Ned Devine (a.k.a. Waking Ned) (1998)',
 'Little Voice (1998)',
 'Name of the Rose, The (Name der Rose, Der) (1986)',
 "Cookie's Fortune (1999)",
 'Election (1999)',
 'Austin Powers: The Spy Who Shagged Me (1999)',
 'Eyes Wide Shut (1999)',
 'Sixth Sense, The (1999)',
 'Thomas Crown Affair, The (1999)',
 'Bowfinger (1999)',
 'Airplane! (1980)',
 'Black Cat, White Cat (Crna macka, beli macor) (1998)',
 'Pajama Game, The (1957)',
 'High Plains Drifter (1973)',
 'Hairspray (1988)',
 'Crimes and Misdemeanors (1989)',
 'Dead Again (1991)',
 'Commitments, The (1991)',
 'Mansfield Park (1999)',
 'All About My Mother (Todo sobre mi madre) (1999)',
 'Magnolia (1999)',
 'Galaxy Quest (1999)',
 'Boys from Brazil, The (1978)',
 'League of Their Own, A (1992)',
 'Wonder Boys (2000)',
 'Defending Your Life (1991)',
 'Searchers, The (1956)',
 'Erin Brockovich (2000)',
 'High Fidelity (2000)',
 'Outlaw Josey Wales, The (1976)',
 'East is East (1999)',
 'Mr. Mom (1983)',
 'Blow-Up (Blowup) (1966)',
 "I'm the One That I Want (2000)",
 'Almost Famous (2000)',
 'Best in Show (2000)',
 'Billy Elliot (2000)',
 'Crouching Tiger, Hidden Dragon (Wo hu cang long) (2000)',
 'Planes, Trains & Automobiles (1987)',
 'Chocolat (2000)',
 'Gift, The (2000)',
 'Before Night Falls (2000)',
 'O Brother, Where Art Thou? (2000)',
 'State and Main (2000)',
 'Thirteen Days (2000)',
 'Traffic (2000)',
 'Legend of Rita, The (Stille nach dem Schuß, Die) (1999)',
 'Innerspace (1987)',
 'In the Mood For Love (Fa yeung nin wa) (2000)',
 'Series 7: The Contenders (2001)',
 'Memento (2000)',
 'Blow (2001)',
 "Bridget Jones's Diary (2001)",
 'Circle, The (Dayereh) (2000)',
 'Visit, The (2000)',
 'Under the Sand (2000)',
 'Moulin Rouge (2001)',
 'Divided We Fall (Musíme si pomáhat) (2000)',
 'Closet, The (Placard, Le) (2001)',
 'Ghost World (2001)',
 'Together (Tillsammans) (2000)',
 'L.I.E. (2001)',
 "Man Who Wasn't There, The (2001)",
 "Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)",
 "Devil's Backbone, The (Espinazo del diablo, El) (2001)",
 "No Man's Land (2001)",
 'Babe (1995)',
 'Dead Man Walking (1995)',
 'Clueless (1995)',
 'Apollo 13 (1995)',
 'Batman Forever (1995)',
 'Interview with the Vampire: The Vampire Chronicles (1994)',
 'Little Women (1994)',
 'Legends of the Fall (1994)',
 'Once Were Warriors (1994)',
 'Quiz Show (1994)',
 'Ace Ventura: Pet Detective (1994)',
 'Lion King, The (1994)',
 'True Lies (1994)',
 'Addams Family Values (1993)',
 'In the Line of Fire (1993)',
 'Remains of the Day, The (1993)',
 'Secret Garden, The (1993)',
 'Shadowlands (1993)',
 'Terminator 2: Judgment Day (1991)',
 'Snow White and the Seven Dwarfs (1937)',
 'Pretty Woman (1990)',
 'Jumanji (1995)',
 'Waiting to Exhale (1995)',
 'Father of the Bride Part II (1995)',
 'Sabrina (1995)',
 'Tom and Huck (1995)',
 'GoldenEye (1995)',
 'American President, The (1995)',
 'Balto (1995)',
 'Cutthroat Island (1995)',
 'Casino (1995)',
 'Sense and Sensibility (1995)',
 'Ace Ventura: When Nature Calls (1995)',
 'Copycat (1995)',
 'Powder (1995)',
 'Leaving Las Vegas (1995)',
 'Othello (1995)',
 'Now and Then (1995)',
 'Richard III (1995)',
 'Restoration (1995)',
 'How to Make an American Quilt (1995)',
 'Big Green, The (1995)',
 'Indian in the Cupboard, The (1995)',
 'Eye for an Eye (1996)',
 "Mr. Holland's Opus (1995)",
 'Bio-Dome (1996)',
 'Lawnmower Man 2: Beyond Cyberspace (1996)',
 'Screamers (1995)',
 'Juror, The (1996)',
 'White Squall (1996)',
 'Dunston Checks In (1996)',
 'Black Sheep (1996)',
 'Nick of Time (1995)',
 'Mary Reilly (1996)',
 'Vampire in Brooklyn (1995)',
 'Broken Arrow (1996)',
 'City Hall (1996)',
 'Mr. Wrong (1996)',
 'Happy Gilmore (1996)',
 'Bridges of Madison County, The (1995)',
 'Rumble in the Bronx (Hont faan kui) (1995)',
 'Before and After (1996)',
 'Down Periscope (1996)',
 'Up Close and Personal (1996)',
 'Birdcage, The (1996)',
 'Bad Boys (1995)',
 'Amazing Panda Adventure, The (1995)',
 'Casper (1995)',
 'Clockers (1995)',
 'Congo (1995)',
 'Crimson Tide (1995)',
 'Die Hard: With a Vengeance (1995)',
 'First Knight (1995)',
 'Hackers (1995)',
 'Jury Duty (1995)',
 'Lord of Illusions (1995)',
 'Mad Love (1995)',
 'Mallrats (1995)',
 'Mighty Morphin Power Rangers: The Movie (1995)',
 'Net, The (1995)',
 'Nine Months (1995)',
 'Reckless (1995)',
 'Scarlet Letter, The (1995)',
 'Something to Talk About (1995)',
 'Species (1995)',
 'Three Wishes (1995)',
 'Under Siege 2: Dark Territory (1995)',
 'Unstrung Heroes (1995)',
 'Walk in the Clouds, A (1995)',
 'Waterworld (1995)',
 "White Man's Burden (1995)",
 'Wild Bill (1995)',
 'Bushwhacked (1995)',
 'Babysitter, The (1995)',
 'Boys on the Side (1995)',
 'Cure, The (1995)',
 'Don Juan DeMarco (1995)',
 'Disclosure (1994)',
 'Dolores Claiborne (1995)',
 'Exit to Eden (1994)',
 'French Kiss (1995)',
 'Forget Paris (1995)',
 'Goofy Movie, A (1995)',
 'Hideaway (1995)',
 'Gordy (1995)',
 'Houseguest (1994)',
 'Heavyweights (Heavy Weights) (1995)',
 'Hunted, The (1995)',
 'I.Q. (1994)',
 'Jefferson in Paris (1995)',
 'Junior (1994)',
 'Just Cause (1995)',
 "Kid in King Arthur's Court, A (1995)",
 'Little Princess, A (1995)',
 'Major Payne (1995)',
 'Love Affair (1994)',
 'Losing Isaiah (1995)',
 "Mary Shelley's Frankenstein (Frankenstein) (1994)",
 'Man of the House (1995)',
 'Milk Money (1994)',
 'Miracle on 34th Street (1994)',
 'My Family (1995)',
 "Nobody's Fool (1994)",
 'Nell (1994)',
 'Natural Born Killers (1994)',
 'Only You (1994)',
 'Poison Ivy II (1996)',
 'Outbreak (1995)',
 'Léon: The Professional (a.k.a. The Professional) (Léon) (1994)',
 'Queen Margot (Reine Margot, La) (1994)',
 'Quick and the Dead, The (1995)',
 'Roommates (1995)',
 'Rent-a-Kid (1995)',
 'Stuart Saves His Family (1995)',
 'Swan Princess, The (1994)',
 'Secret of Roan Inish, The (1994)',
 'Specialist, The (1994)',
 'Santa Clause, The (1994)',
 'Tank Girl (1995)',
 'Star Trek: Generations (1994)',
 'Tales from the Hood (1995)',
 'Village of the Damned (1995)',
 'Walking Dead, The (1995)',
 "What's Eating Gilbert Grape (1993)",
 'While You Were Sleeping (1995)',
 'War, The (1994)',
 'Baby-Sitters Club, The (1995)',
 'Bitter Moon (1992)',
 'Client, The (1994)',
 'Crooklyn (1994)',
 'Crow, The (1994)',
 'Cobb (1994)',
 'Flintstones, The (1994)',
 'Higher Learning (1995)',
 'I Like It Like That (1994)',
 'I Love Trouble (1994)',
 'It Could Happen to You (1994)',
 "Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A) (1994)",
 'Naked Gun 33 1/3: The Final Insult (1994)',
 'Paper, The (1994)',
 'Richie Rich (1994)',
 'Speed (1994)',
 'Speechless (1994)',
 'When a Man Loves a Woman (1994)',
 'Wolf (1994)',
 'Wyatt Earp (1994)',
 'Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension) (1994)',
 'Age of Innocence, The (1993)',
 'Another Stakeout (1993)',
 'Bad Girls (1994)',
 'Beverly Hillbillies, The (1993)',
 'Body Snatchers (1993)',
 "City Slickers II: The Legend of Curly's Gold (1994)",
 'Cliffhanger (1993)',
 'Coneheads (1993)',
 'Cops and Robbersons (1994)',
 'Dave (1993)',
 'Fatal Instinct (1993)',
 'Firm, The (1993)',
 'Free Willy (1993)',
 'Geronimo: An American Legend (1993)',
 'Getting Even with Dad (1994)',
 'Hot Shots! Part Deux (1993)',
 'Englishman Who Went Up a Hill But Came Down a Mountain, The (1995)',
 'House of the Spirits, The (1993)',
 "I'll Do Anything (1994)",
 "What's Love Got to Do with It? (1993)",
 'Last Action Hero (1993)',
 'Made in America (1993)',
 'Malice (1993)',
 'Man Without a Face, The (1993)',
 'Menace II Society (1993)',
 'Executive Decision (1996)',
 'Much Ado About Nothing (1993)',
 'Next Karate Kid, The (1994)',
 'North (1994)',
 'Philadelphia (1993)',
 'Poetic Justice (1993)',
 'Renaissance Man (1994)',
 'Robin Hood: Men in Tights (1993)',
 'Rudy (1993)',
 'Serial Mom (1994)',
 'Simple Twist of Fate, A (1994)',
 'Sirens (1994)',
 'Sliver (1993)',
 'Son in Law (1993)',
 'Super Mario Bros. (1993)',
 'Terminal Velocity (1994)',
 'Little Big League (1994)',
 'Little Rascals, The (1994)',
 'Ghost (1990)',
 'Candyman: Farewell to the Flesh (1995)',
 'Homeward Bound II: Lost in San Francisco (1996)',
 'Aristocats, The (1970)',
 'Primal Fear (1996)',
 'All Dogs Go to Heaven 2 (1996)',
 'Sgt. Bilko (1996)',
 'Diabolique (1996)',
 'Fear (1996)',
 'Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite) (1996)',
 'Substitute, The (1996)',
 'Feeling Minnesota (1996)',
 'Angus (1995)',
 'Quest, The (1996)',
 'Oliver & Company (1988)',
 'Celtic Pride (1996)',

## **steps of Neighborhod based CF**: Cosine Similarity

In [230]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

In [231]:
ratings_pivot_raw

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [232]:
initial = ratings_pivot_raw.T
initial

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,NaN,4.5,NaN,NaN
xXx (2002),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,2.0
xXx: State of the Union (2005),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5
¡Three Amigos! (1986),4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
À nous la liberté (Freedom for Us) (1931),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [233]:
user_item = initial.fillna(0)
user_item

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Salem's Lot (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Til There Was You (1997),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,2.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5
¡Three Amigos! (1986),4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Cosine Similarity
+ Angle measurement between two vectors. Orientation, not magnitude.
+ Values range between:
  
    -1: vectors point in opposite directions.
  
    +1: vectors are on top of each other.
    
     0: vectors are perpendicular. 

$$cos(X, Y) = \frac{\sum_i^n{x_i*y_i}}{\sqrt{\sum_i^n{x_i^2}}\sqrt{\sum_i^n{y_i^2}}}$$

Numerator: dot product of the vectors

Denominator: Euclidean norm of the vectors multiplied

In [234]:
# define the function that calculates the above equation

def cos_sim(vec_one, vec_two):
    num = np.dot(vec_one, vec_two)
    denom = np.sqrt(np.dot(vec_one, vec_one)) * np.sqrt(np.dot(vec_two, vec_two))
    return round(num/denom, 2)

In [235]:
# small test for the function

vec_one = [2,3,1]
vec_two = [3,4,5]

sim_score = cos_sim(vec_one, vec_two)

sim_score

0.87

In [236]:
user_item[610]

title
'71 (2014)                                   4.0
'Hellboy': The Seeds of Creation (2004)      0.0
'Round Midnight (1986)                       0.0
'Salem's Lot (2004)                          0.0
'Til There Was You (1997)                    0.0
                                            ...
eXistenZ (1999)                              0.0
xXx (2002)                                   2.0
xXx: State of the Union (2005)               1.5
¡Three Amigos! (1986)                        0.0
À nous la liberté (Freedom for Us) (1931)    0.0
Name: 610, Length: 9719, dtype: float64

In [237]:
user_item.columns

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            601, 602, 603, 604, 605, 606, 607, 608, 609, 610],
           dtype='int64', name='userId', length=610)

In [238]:
# let's try it on the data

#vec_one, vec_two = [user_item["Dina"], user_item["Tiago"]]
vec_one, vec_two = [user_item[610], user_item[1]]

sim_score = cos_sim(vec_one, vec_two)

sim_score

0.15

In [239]:
# create a dataframe for the cosine similarity score for each pair of users of size 15x15

def user_user_matrix(df):
    total_fillable = list()
    for user in df.columns:
        fillable = list()
        for other_user in df.columns:
            sim_score = cos_sim(df[user], df[other_user])
            fillable.append(sim_score)
        
        total_fillable.append(fillable)

    return pd.DataFrame(total_fillable, columns = df.columns, index = df.columns)

#### Create a table with pairwise cosine-similarities

In [240]:
user_user = user_user_matrix(user_item)
user_user

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.00,0.03,0.06,0.19,0.13,0.13,0.16,0.14,0.06,0.02,...,0.08,0.16,0.22,0.07,0.15,0.16,0.27,0.29,0.09,0.15
2,0.03,1.00,0.00,0.00,0.02,0.03,0.03,0.03,0.00,0.07,...,0.20,0.02,0.01,0.00,0.00,0.03,0.01,0.05,0.03,0.10
3,0.06,0.00,1.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,...,0.01,0.01,0.03,0.00,0.01,0.01,0.02,0.02,0.00,0.03
4,0.19,0.00,0.00,1.00,0.13,0.09,0.12,0.06,0.01,0.03,...,0.09,0.13,0.31,0.05,0.08,0.20,0.13,0.15,0.03,0.11
5,0.13,0.02,0.01,0.13,1.00,0.30,0.11,0.43,0.00,0.03,...,0.07,0.42,0.11,0.26,0.15,0.11,0.15,0.14,0.26,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.16,0.03,0.01,0.20,0.11,0.10,0.20,0.10,0.08,0.09,...,0.18,0.12,0.30,0.07,0.15,1.00,0.15,0.26,0.07,0.20
607,0.27,0.01,0.02,0.13,0.15,0.16,0.19,0.19,0.01,0.01,...,0.09,0.20,0.20,0.14,0.12,0.15,1.00,0.28,0.15,0.14
608,0.29,0.05,0.02,0.15,0.14,0.18,0.32,0.19,0.10,0.08,...,0.16,0.20,0.23,0.16,0.18,0.26,0.28,1.00,0.12,0.32
609,0.09,0.03,0.00,0.03,0.26,0.21,0.09,0.42,0.00,0.02,...,0.04,0.34,0.06,0.24,0.10,0.07,0.15,0.12,1.00,0.05
610,0.15,0.10,0.03,0.11,0.06,0.05,0.19,0.08,0.07,0.12,...,0.22,0.09,0.16,0.05,0.12,0.20,0.14,0.32,0.05,1.00

In [241]:
# We can create the "user_user"-matrix (including the similarities between users) using sklearn

user_user_sklearn = cosine_similarity(user_item.T)
user_user_sklearn = pd.DataFrame(user_user_sklearn, columns = user_item.columns, index = user_item.columns).round(2)

In [242]:
user_user_sklearn

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.00,0.03,0.06,0.19,0.13,0.13,0.16,0.14,0.06,0.02,...,0.08,0.16,0.22,0.07,0.15,0.16,0.27,0.29,0.09,0.15
2,0.03,1.00,0.00,0.00,0.02,0.03,0.03,0.03,0.00,0.07,...,0.20,0.02,0.01,0.00,0.00,0.03,0.01,0.05,0.03,0.10
3,0.06,0.00,1.00,0.00,0.01,0.00,0.00,0.01,0.00,0.00,...,0.01,0.01,0.03,0.00,0.01,0.01,0.02,0.02,0.00,0.03
4,0.19,0.00,0.00,1.00,0.13,0.09,0.12,0.06,0.01,0.03,...,0.09,0.13,0.31,0.05,0.08,0.20,0.13,0.15,0.03,0.11
5,0.13,0.02,0.01,0.13,1.00,0.30,0.11,0.43,0.00,0.03,...,0.07,0.42,0.11,0.26,0.15,0.11,0.15,0.14,0.26,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.16,0.03,0.01,0.20,0.11,0.10,0.20,0.10,0.08,0.09,...,0.18,0.12,0.30,0.07,0.15,1.00,0.15,0.26,0.07,0.20
607,0.27,0.01,0.02,0.13,0.15,0.16,0.19,0.19,0.01,0.01,...,0.09,0.20,0.20,0.14,0.12,0.15,1.00,0.28,0.15,0.14
608,0.29,0.05,0.02,0.15,0.14,0.18,0.32,0.19,0.10,0.08,...,0.16,0.20,0.23,0.16,0.18,0.26,0.28,1.00,0.12,0.32
609,0.09,0.03,0.00,0.03,0.26,0.21,0.09,0.42,0.00,0.02,...,0.04,0.34,0.06,0.24,0.10,0.07,0.15,0.12,1.00,0.05
610,0.15,0.10,0.03,0.11,0.06,0.05,0.19,0.08,0.07,0.12,...,0.22,0.09,0.16,0.05,0.12,0.20,0.14,0.32,0.05,1.00

### With this matrix, we can create recommendations:

+ create a list of unseen movies of the active user (i.e. candidates list)


+ for each unseen movie: check who has rated it and who is closest to the active user, then predict the rating based on the (weighted) average ratings of the neighbours (the number of neighbors to include is a hyperparameter)


+ sort and select top recommendations

(This can all be done with merely writing for-loops and comparing values)

In [243]:
# Step 1: Choose an active user
active_user = 10

In [244]:
items = initial.index

In [245]:
items

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]² (2009)',
       '[REC]³ 3 Génesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', name='title', length=9719)

In [246]:
# Step 2: Create a list of unseen movies for the active user

# notice that I am using the initial matrix with the NAs to locate unseen movies for a user

candidates = initial[initial[active_user].isna()].index
candidates

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]² (2009)',
       '[REC]³ 3 Génesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', name='title', length=9579)

In [247]:
user_user[active_user].sort_values(ascending= False)

userId
10     1.00
159    0.29
143    0.27
563    0.26
177    0.25
       ...
71     0.00
505    0.00
355    0.00
262    0.00
451    0.00
Name: 10, Length: 610, dtype: float64

In [248]:
# Step 3: Create a list of top 5 similar user, i.e. neighbors

neighbors = user_user[active_user].sort_values(ascending= False).index[1:6]
neighbors

Int64Index([159, 143, 563, 177, 189], dtype='int64', name='userId')

In [249]:
candidates

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]² (2009)',
       '[REC]³ 3 Génesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', name='title', length=9579)

In [250]:
items        = []
pred_ratings = []

for item in candidates:
    #extract users who have rated unseen movies
    other_users = initial.columns[~initial.loc[item].isna()]
    # we want to create an intersection, so we save the users as a set-object
    other_users = set(other_users)

    num = 0
    den = 0
    
    for neighbor in set(neighbors).intersection(other_users): 
        ratings   = user_item[neighbor][item] 
        sim_score = user_user[active_user][neighbor]
        num       = num + (ratings*sim_score)
        den       = den + sim_score + 0.000001
    
    pred_rating = num/(den + 0.000001)
    
    items.append(item)
    pred_ratings.append(pred_rating)

In [251]:
predictions_df = pd.DataFrame(data={'item': items, 'pred_ratings': pred_ratings})
predictions_df

                                           item  pred_ratings
0                                    '71 (2014)           0.0
1       'Hellboy': The Seeds of Creation (2004)           0.0
2                        'Round Midnight (1986)           0.0
3                           'Salem's Lot (2004)           0.0
4                     'Til There Was You (1997)           0.0
...                                         ...           ...
9574                            eXistenZ (1999)           0.0
9575                                 xXx (2002)           0.0
9576             xXx: State of the Union (2005)           0.0
9577                      ¡Three Amigos! (1986)           0.0
9578  À nous la liberté (Freedom for Us) (1931)           0.0

[9579 rows x 2 columns]

In [252]:
predictions_df.sort_values(by='pred_ratings', ascending=False)

                                           item  pred_ratings
3513                   Good Will Hunting (1997)      4.999972
3865                      Hidden Figures (2016)      4.999966
1061                 Bill Cosby, Himself (1983)      4.999963
3003                            Fired Up (2009)      4.999963
3832                       Hello, Dolly! (1969)      4.999962
...                                         ...           ...
3348                            Get Hard (2015)      0.000000
3347                          Get Carter (2000)      0.000000
3346                          Get Carter (1971)      0.000000
3345                               Gerry (2002)      0.000000
9578  À nous la liberté (Freedom for Us) (1931)      0.000000

[9579 rows x 2 columns]